"""HealthConfig — loads `.repowise/health-rules.json` per-file overrides.

The file is **user-authored** (it isn't generated by Repowise). It lets
teams silence specific biomarkers on legacy paths, or globally tune the
detector list. Decisions deliberately kept narrow in v1:

- Repo-wide ``disabled_biomarkers``: detectors that never fire.
- Per-path ``rules``: a list of glob → ``disabled_biomarkers`` entries.
  First matching glob wins. Patterns use ``fnmatch`` semantics over the
  repo-relative POSIX path (``src/legacy/**.py``).

Schema (validated on load, errors logged but never raised):

    {
      "disabled_biomarkers": ["dry_violation"],
      "rules": [
        {"path": "src/legacy/**", "disabled_biomarkers": ["complex_method"]},
        {"path": "**/*.generated.ts", "disabled_biomarkers": ["large_method"]}
      ]
    }
"""

from __future__ import annotations

import fnmatch
import json
from dataclasses import dataclass, field
from pathlib import Path

import structlog

from repowise.core.repo_config import get_repowise_dir

log = structlog.get_logger(__name__)


HEALTH_RULES_FILENAME = "health-rules.json"


@dataclass
class HealthRule:
    """One per-path override entry."""

    path_glob: str
    disabled_biomarkers: list[str] = field(default_factory=list)


@dataclass
class HealthConfig:
    """Loaded health configuration. Empty when no rules file exists."""

    disabled_biomarkers: list[str] = field(default_factory=list)
    rules: list[HealthRule] = field(default_factory=list)

    @classmethod
    def load(cls, repo_path: Path | str) -> HealthConfig:
        """Load `.repowise/health-rules.json` for *repo_path*.

        Missing file → empty config. Malformed file → empty config + a
        single warning log. Never raises.
        """
        rules_path = get_repowise_dir(repo_path) / HEALTH_RULES_FILENAME
        if not rules_path.exists():
            return cls()
        try:
            raw = json.loads(rules_path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            log.warning("health_rules_load_failed", path=str(rules_path), error=str(exc))
            return cls()
        return cls.from_dict(raw)

    @classmethod
    def from_dict(cls, raw: object) -> HealthConfig:
        if not isinstance(raw, dict):
            return cls()
        disabled: list[str] = [
            str(b) for b in (raw.get("disabled_biomarkers") or []) if isinstance(b, str)
        ]
        rules: list[HealthRule] = []
        for entry in raw.get("rules") or []:
            if not isinstance(entry, dict):
                continue
            glob = entry.get("path") or entry.get("path_glob")
            if not isinstance(glob, str) or not glob:
                continue
            disabled_for = [
                str(b)
                for b in (entry.get("disabled_biomarkers") or [])
                if isinstance(b, str)
            ]
            rules.append(HealthRule(path_glob=glob, disabled_biomarkers=disabled_for))
        return cls(disabled_biomarkers=disabled, rules=rules)

    def per_file_disabled(self, file_paths: list[str]) -> dict[str, set[str]]:
        """Materialize per-path overrides.

        Walks *file_paths*, matches each path against this config's
        rules, and returns a `{path: {biomarker, ...}}` map suitable
        for the ``HealthAnalyzer.analyze`` ``config`` dict.
        """
        if not self.rules:
            return {}
        out: dict[str, set[str]] = {}
        for path in file_paths:
            norm = path.replace("\\", "/")
            disabled: set[str] = set()
            for rule in self.rules:
                if fnmatch.fnmatchcase(norm, rule.path_glob):
                    disabled.update(rule.disabled_biomarkers)
            if disabled:
                out[path] = disabled
        return out

    def to_analyzer_config(self, file_paths: list[str]) -> dict[str, object]:
        """Return the dict accepted by ``HealthAnalyzer.analyze``."""
        return {
            "disabled_biomarkers": list(self.disabled_biomarkers),
            "per_file_disabled": self.per_file_disabled(file_paths),
        }
