"""Where a file's code comes from, and so whether it ships.

Sibling of :mod:`repowise.core.test_paths` and :mod:`repowise.core.support_paths`.
Those answer one question each; this one picks the single origin a ranked
surface needs before it can put a file at the top of a fix list. A tutorial
under ``docs_src/`` or a vendored ``typeahead.jquery.js`` can carry a perfectly
real finding that nobody should be asked to fix first.

The answer is one of :data:`CODE_ORIGINS`, decided in precedence order, so a
file has exactly one: ``generated`` beats ``vendored`` beats ``test`` beats
``docs_example`` beats ``tooling``, and everything else is ``production``.

The generated-file banner rule is the one ingestion already applies before it
indexes a file (:func:`is_generated_header`, moved here from the traverser so
both read one rule). Ingestion also drops ``vendor/``, ``node_modules/`` and
``*.min.js`` before analysis ever sees them; they are classified here anyway so
a caller holding a bare path gets the same answer.
"""

from __future__ import annotations

import re
from functools import lru_cache
from pathlib import PurePosixPath
from typing import Literal

from .support_paths import EXAMPLE_DIR_TOKENS
from .test_paths import is_test_related_path

__all__ = [
    "CODE_ORIGINS",
    "CodeOrigin",
    "code_origin",
    "is_generated_header",
]

CodeOrigin = Literal["production", "test", "vendored", "docs_example", "generated", "tooling"]

CODE_ORIGINS: tuple[CodeOrigin, ...] = (
    "production",
    "test",
    "vendored",
    "docs_example",
    "generated",
    "tooling",
)

# --------------------------------------------------------------------------
# Generated
# --------------------------------------------------------------------------

# Generated-file banners, read only from comment lines and docstring openers
# in the first two lines. These two count anywhere in the comment text:
_GENERATED_ANYWHERE_MARKERS: tuple[str, ...] = ("DO NOT EDIT", "@GENERATED")
# ...these only where the comment text starts ("<auto-generated>" included):
_GENERATED_LEADING_MARKERS: tuple[str, ...] = (
    "CODE GENERATED",
    "THIS FILE WAS AUTOMATICALLY GENERATED",
    "GENERATED CODE",
    "AUTO-GENERATED",
)
# ...plus the sentence that says it anywhere in the comment.
_THIS_FILE_GENERATED_RE = re.compile(
    r"\bTHIS FILE (?:IS|WAS) (?:AUTO-?|AUTOMATICALLY )?GENERATED\b"
)
# Longest first, so "/*" is stripped whole rather than as "/".
_COMMENT_PREFIXES: tuple[str, ...] = ("<!--", "//", "/*", "--", "#", "*", ";")
_DOCSTRING_OPENER_RE = re.compile(r"""^[rRuUbB]?(?:\"\"\"|''')""")

_GENERATED_DIR_TOKENS = frozenset({"__generated__"})


def _comment_text(line: str, in_docstring: bool) -> str | None:
    """The text of a comment line or docstring opener, None for anything else."""
    if in_docstring:
        return line
    if opener := _DOCSTRING_OPENER_RE.match(line):
        return line[opener.end() :].strip()
    for prefix in _COMMENT_PREFIXES:
        if line.startswith(prefix):
            return line[len(prefix) :].strip()
    return None


def _is_banner(text: str) -> bool:
    """Whether upper-cased comment *text* declares its file generated."""
    if any(marker in text for marker in _GENERATED_ANYWHERE_MARKERS):
        return True
    if _THIS_FILE_GENERATED_RE.search(text):
        return True
    # Leading punctuation is decoration ("<auto-generated>", "*** GENERATED").
    lead = text.lstrip("<!*-=#/; \t")
    return lead.startswith(_GENERATED_LEADING_MARKERS)


def is_generated_header(header: str) -> bool:
    """Whether the first two lines of *header* carry a generated-file banner.

    A banner sits in a comment or a module docstring. Code and prose that
    merely mention codegen (a string literal "Auto-generated by ...", a
    docstring about "the auto-generated client") are not banners.
    """
    in_docstring = False
    for line in header.splitlines()[:2]:
        text = _comment_text(line.strip(), in_docstring)
        if text is None:
            continue
        # A bare opener ('"""' alone) puts the docstring text on the next line.
        in_docstring = not text and bool(_DOCSTRING_OPENER_RE.match(line.strip()))
        if _is_banner(text.upper()):
            return True
    return False


@lru_cache(maxsize=1)
def _generated_suffixes() -> tuple[str, ...]:
    # Deferred: the ingestion package imports the traverser, which imports
    # this module for the banner rule above.
    from .ingestion.languages.registry import REGISTRY

    return tuple(sorted(REGISTRY.generated_suffixes()))


def _is_generated_name(name: str) -> bool:
    return ".generated." in name or name.endswith(_generated_suffixes())


# --------------------------------------------------------------------------
# Vendored
# --------------------------------------------------------------------------

_VENDORED_DIR_TOKENS = frozenset(
    {
        "vendor",
        "vendors",
        "third_party",
        "thirdparty",
        "third-party",
        "node_modules",
        "bower_components",
        "site-packages",
    }
)
# Matched only as the first segment: ``pkg/external/`` is as often a package
# that talks to external services as it is a copy of someone else's code.
_VENDORED_ROOT_TOKENS = frozenset({"external", "externals"})
_MINIFIED_SUFFIXES = (".min.js", ".min.css", ".min.mjs")

# A copied library is recognisable by its header only in the directories a
# site serves assets from. Anywhere else a license header is far more often
# the repository's own.
_ASSET_DIR_TOKENS = frozenset({"docs", "doc", "static", "assets", "public", "_static"})
_HEADER_LINES = 20
_LICENSE_RE = re.compile(
    r"copyright|\(c\)|©|@license|licen[cs]ed\s+under|released\s+under|\bMIT\b",
    re.IGNORECASE,
)
# What says the header names a project and its release, rather than an owner:
# a preserved banner, a license tag, or "<name> v1.2" / "<name>.js 0.10.5".
_BANNER_RE = re.compile(
    r"/\*!|@license|@preserve|\b[A-Za-z][\w.\-]*\s+v?\d+\.\d+(?:\.\d+)?\b"
)


def _comment_lines(header: str) -> list[str]:
    lines: list[str] = []
    for raw in header.splitlines()[:_HEADER_LINES]:
        text = _comment_text(raw.strip(), False)
        if text is not None:
            lines.append(text)
    return lines


def _squash(text: str) -> str:
    """Lowercase alphanumerics only, so ``my-lib`` and ``MyLib`` compare equal."""
    return re.sub(r"[^0-9a-z]", "", text.lower())


def _third_party_header(header: str, project: str | None) -> bool:
    """Whether the leading comments carry another project's license banner.

    Conservative on purpose: it needs a license or copyright line **and** a
    versioned or preserved banner, both in comments, and the banner must not
    name *project* when the caller knows it. A repository's own
    ``Copyright (c) 2024 Acme`` header has no release banner, so it stays.
    """
    comments = "\n".join(_comment_lines(header))
    if not comments or not _LICENSE_RE.search(comments) or not _BANNER_RE.search(comments):
        return False
    return not (project and _squash(project) in _squash(comments))


# --------------------------------------------------------------------------
# Docs, examples, tooling
# --------------------------------------------------------------------------

# Docs roots count at any depth. Docs are the plural and FastAPI's ``docs_src``
# only: a singular ``doc/`` is as often a shipped package (cobra's ``doc``
# generates man pages) as a documentation tree.
_DOCS_ROOT_TOKENS = frozenset({"docs", "docs_src"})
# Examples as ``support_paths`` reads them, less the benchmark harnesses, which
# run the system (tooling below). Unlike ``support_paths`` these count only as
# the first segment or directly under a docs root: ``src/pkg/examples/`` is
# as often shipped code (an example registry, a runner) as a sample.
_EXAMPLE_TOKENS = EXAMPLE_DIR_TOKENS - {"bench", "benches", "benchmarks"}
_TUTORIAL_PREFIX = "tutorial"


def _is_example_dir(segment: str) -> bool:
    return segment in _EXAMPLE_TOKENS or segment.startswith(_TUTORIAL_PREFIX)


def _is_docs_example(dirs: list[str]) -> bool:
    # Anything under a docs root already counts, examples beneath it included.
    return any(d in _DOCS_ROOT_TOKENS for d in dirs) or bool(dirs and _is_example_dir(dirs[0]))


# Close to ``perf/causal.py``'s tooling parts, with two differences: the
# benchmark spellings ``bench`` / ``benches`` join ``benchmarks``, and there is
# no ``/cli/`` rule, since a CLI's source ships and its findings are real work.
# Migrations join too: they run once at deploy time and are append-only.
_TOOLING_DIR_TOKENS = frozenset(
    {
        ".github",
        "bench",
        "benches",
        "benchmarks",
        "build",
        "devtools",
        "scripts",
        "tooling",
        "tools",
        "migrations",
    }
)
_TOOLING_ROOT_NAMES = frozenset(
    {"setup.py", "noxfile.py", "fabfile.py", "Rakefile", "Gruntfile.js"}
)
_TOOLING_NAME_RE = re.compile(
    r"^(?:gulpfile|webpack\.config|vite\.config|rollup\.config|eslint\.config|"
    r"jest\.config|vitest\.config|babel\.config|karma\.conf)\.[cm]?[jt]s$"
)


def _header_text(text: str | bytes | None) -> str:
    if text is None:
        return ""
    if isinstance(text, bytes):
        # Twenty lines of a hand-written file fit in 4 KB; a minified bundle
        # has no newlines, and its first 4 KB says as much as the rest.
        return text[:4096].decode("utf-8", errors="ignore")
    return text[:4096]


def code_origin(
    path: str,
    text: str | bytes | None = None,
    *,
    is_test: bool | None = None,
    project: str | None = None,
) -> CodeOrigin:
    """The one origin of the file at repo-relative *path*.

    *text* is the file's content, or just its head; only the first 20 lines
    are read. Without it the content rules (generated banner, third-party
    license header) cannot fire and the answer rests on the path.

    *is_test* is the flag ingestion stored, when the caller has it. ``None``
    derives it from the path with the shared test classifier.

    *project* is the repository's name, so its own release banner is not
    taken for someone else's.
    """
    normalized = path.replace("\\", "/")
    parts = PurePosixPath(normalized).parts
    if not parts:
        return "production"
    name = parts[-1]
    dirs = [p.lower() for p in parts[:-1]]
    header = _header_text(text)

    if (
        _is_generated_name(name)
        or any(d in _GENERATED_DIR_TOKENS for d in dirs)
        or (header and is_generated_header(header))
    ):
        return "generated"

    lowered_name = name.lower()
    if (
        any(d in _VENDORED_DIR_TOKENS for d in dirs)
        or (dirs and dirs[0] in _VENDORED_ROOT_TOKENS)
        or lowered_name.endswith(_MINIFIED_SUFFIXES)
        or (
            header
            and any(d in _ASSET_DIR_TOKENS for d in dirs)
            and _third_party_header(header, project)
        )
    ):
        return "vendored"

    if is_test if is_test is not None else is_test_related_path(normalized):
        return "test"

    if _is_docs_example(dirs):
        return "docs_example"

    if (
        any(d in _TOOLING_DIR_TOKENS for d in dirs)
        or "/alembic/versions/" in f"/{normalized.lower()}"
        or (not dirs and name in _TOOLING_ROOT_NAMES)
        or _TOOLING_NAME_RE.match(lowered_name)
    ):
        return "tooling"

    return "production"
