"""Where a file's code comes from, and so whether it ships.

Sibling of :mod:`repowise.core.test_paths` and :mod:`repowise.core.support_paths`.
Those answer one question each; this one picks the single origin a ranked
surface needs before it can put a file at the top of a fix list. A tutorial
under ``docs_src/`` or a vendored ``typeahead.jquery.js`` can carry a perfectly
real finding that nobody should be asked to fix first.

The answer is one of :data:`CODE_ORIGINS`, decided in precedence order, so a
file has exactly one: ``generated`` beats ``vendored`` beats ``build`` beats
``test`` beats ``docs_example`` beats ``tooling``, and everything else is
``production``. ``build`` is decided by the file's type (a Gradle script, a
``CMakeLists.txt``, a bundler config), wherever it sits; :func:`is_build_file`
answers it for a caller that needs only that.

The generated-file banner rule is the one ingestion already applies before it
indexes a file (:func:`is_generated_header`, moved here from the traverser so
both read one rule); classification adds a "this class is generated" sentence
further down the head, which is too weak to drop a file from the graph but
enough to keep it out of a fix list. Ingestion also drops ``vendor/``, ``node_modules/`` and
``*.min.js`` before analysis ever sees them; they are classified here anyway so
a caller holding a bare path gets the same answer.
"""

from __future__ import annotations

import re
from functools import cache, lru_cache
from itertools import pairwise
from pathlib import PurePosixPath
from typing import Literal

from .support_paths import EXAMPLE_DIR_TOKENS
from .test_paths import is_test_related_path

__all__ = [
    "CODE_ORIGINS",
    "CodeOrigin",
    "code_origin",
    "is_build_file",
    "is_generated_header",
    "is_migration_path",
    "is_vendored_or_generated_path",
    "path_origin",
    "ship_rank",
]

CodeOrigin = Literal[
    "production", "test", "vendored", "docs_example", "generated", "tooling", "build"
]

CODE_ORIGINS: tuple[CodeOrigin, ...] = (
    "production",
    "test",
    "vendored",
    "docs_example",
    "generated",
    "tooling",
    "build",
)

# --------------------------------------------------------------------------
# Generated
# --------------------------------------------------------------------------

# Generated-file banners, read only from comment lines and docstring openers
# in the first two lines. These two count anywhere in the comment text:
_GENERATED_ANYWHERE_MARKERS: tuple[str, ...] = ("DO NOT EDIT", "@GENERATED")
# ...these only where the comment text starts ("<auto-generated>" included):
_GENERATED_LEADING_MARKERS: tuple[str, ...] = (
    "CODE GENERATED",
    "THIS FILE WAS AUTOMATICALLY GENERATED",
    "GENERATED CODE",
    "AUTO-GENERATED",
)
# ...plus the sentence that says it anywhere in the comment.
_THIS_FILE_GENERATED_RE = re.compile(
    r"\bTHIS FILE (?:IS|WAS) (?:AUTO-?|AUTOMATICALLY )?GENERATED\b"
)
# Longest first, so "/*" is stripped whole rather than as "/".
_COMMENT_PREFIXES: tuple[str, ...] = ("<!--", "//", "/*", "--", "#", "*", ";")
_DOCSTRING_OPENER_RE = re.compile(r"""^[rRuUbB]?(?:\"\"\"|''')""")

# Output directories of code generators: Relay/GraphQL's ``__generated__`` and
# the Gradle/Maven ``generated-src`` / ``generated-sources`` count anywhere.
# A bare ``generated/`` counts only as a build output (``src/main/generated``,
# ``build/generated``, ``target/generated``): ``app/generated/`` can be
# hand-written code about something generated.
_GENERATED_DIR_TOKENS = frozenset({"__generated__", "generated-src", "generated-sources"})
_GENERATED_BUILD_DIR = "generated"
_BUILD_OUTPUT_PARENTS = frozenset({"main", "build", "target"})
# Beyond the first two lines, only an explicit sentence in a comment counts:
# Java generators put "This class is generated." in the class Javadoc, after
# the license and the imports. The looser markers ("DO NOT EDIT") stay
# first-lines-only, since a hand-written file can ask readers not to edit a
# table further down. The sentence is read from source files only, and only
# up to the first line of code that is not an import, so a template or a
# generator script that prints the banner into its output is not taken for
# the output.
#
# The sentence must also say it is machine output: generated automatically,
# by or from something, or not to be edited ("Edit X instead"). "This file is
# generated when you run make docs" describes a hand-written file.
_GENERATED_SENTENCE_RE = re.compile(
    r"\bTHIS (?:CLASS|FILE) (?:IS|WAS) (?:"
    r"(?:AUTO-?|AUTOMATICALLY )GENERATED\b"
    r"|GENERATED (?:BY|FROM)\b"
    r"|GENERATED\b.*(?:\bINSTEAD\b|\bDO NOT (?:HAND[- ])?(?:EDIT|MODIFY)|\bNOT BE (?:EDITED|MODIFIED))"
    r")"
)
_GENERATED_SENTENCE_LINES = 40
_PREAMBLE_PREFIXES = ("package ", "import ", "from ", "using ")


def _comment_text(line: str, in_docstring: bool) -> str | None:
    """The text of a comment line or docstring opener, None for anything else."""
    if in_docstring:
        return line
    if opener := _DOCSTRING_OPENER_RE.match(line):
        return line[opener.end() :].strip()
    for prefix in _COMMENT_PREFIXES:
        if line.startswith(prefix):
            return line[len(prefix) :].strip()
    return None


def _is_banner(text: str) -> bool:
    """Whether upper-cased comment *text* declares its file generated."""
    if any(marker in text for marker in _GENERATED_ANYWHERE_MARKERS):
        return True
    if _THIS_FILE_GENERATED_RE.search(text):
        return True
    # Leading punctuation is decoration ("<auto-generated>", "*** GENERATED").
    lead = text.lstrip("<!*-=#/; \t")
    return lead.startswith(_GENERATED_LEADING_MARKERS)


def is_generated_header(header: str) -> bool:
    """Whether the first two lines of *header* carry a generated-file banner.

    A banner sits in a comment or a module docstring. Code and prose that
    merely mention codegen (a string literal "Auto-generated by ...", a
    docstring about "the auto-generated client") are not banners.
    """
    in_docstring = False
    for line in header.splitlines()[:2]:
        text = _comment_text(line.strip(), in_docstring)
        if text is None:
            continue
        # A bare opener ('"""' alone) puts the docstring text on the next line.
        in_docstring = not text and bool(_DOCSTRING_OPENER_RE.match(line.strip()))
        if _is_banner(text.upper()):
            return True
    return False


def _declares_generated(name: str, header: str) -> bool:
    """Whether a comment in the file's head says the file or class is generated.

    Code analysis only: ingestion's skip rule stays :func:`is_generated_header`,
    because skipping drops a file from the graph and its callers lose edges.
    """
    if is_generated_header(header):
        return True
    return name.lower().endswith(_code_suffixes()) and _leading_generated_sentence(header)


def _leading_generated_sentence(header: str) -> bool:
    """The generated sentence in a comment before the first line of real code."""
    lines = [line.strip() for line in header.splitlines()[:_GENERATED_SENTENCE_LINES]]
    for i, line in enumerate(lines):
        text = _comment_text(line, False) if line else ""
        if text is None:
            if not line.startswith(_PREAMBLE_PREFIXES):
                return False
        elif _GENERATED_SENTENCE_RE.search(text.upper()) and not _above_import(lines, i):
            return True
    return False


def _above_import(lines: list[str], i: int) -> bool:
    """A comment right above an import is about that import ("this file is
    generated at build time" over the import of a build artifact)."""
    return i + 1 < len(lines) and lines[i + 1].startswith(_PREAMBLE_PREFIXES)


# .NET reference assemblies (``src/libraries/<Lib>/ref/<Lib>.cs``) declare the
# public API with ``throw null`` bodies; the implementation under ``src/``
# carries the code. Counted as generated because they are consumed the same
# way: tooling regenerates them and nothing in them is a place to fix code.
# The path alone is not enough (a ``ref/`` folder can hold anything), so a
# ``{ throw null; }`` member body or the API-review banner must show in the head.
_REFERENCE_STUB_RE = re.compile(
    r"\{\s*throw null;\s*\}|^// Changes to this file must follow the https://aka\.ms/api-review",
    re.MULTILINE,
)


def _is_reference_stub(name: str, dirs: list[str], header: str) -> bool:
    return (
        name.lower().endswith(".cs")
        and "ref" in dirs
        and _REFERENCE_STUB_RE.search(header) is not None
    )


# Deferred registry reads: the ingestion package imports the traverser, which
# imports this module for the banner rule above.
@cache
def _code_suffixes() -> tuple[str, ...]:
    from .ingestion.languages.registry import REGISTRY

    return tuple(sorted(REGISTRY.all_code_extensions()))


@cache
def _generated_suffixes() -> tuple[str, ...]:
    from .ingestion.languages.registry import REGISTRY

    return tuple(sorted(REGISTRY.generated_suffixes()))


def _is_generated_name(name: str) -> bool:
    return ".generated." in name or name.endswith(_generated_suffixes())


# --------------------------------------------------------------------------
# Vendored
# --------------------------------------------------------------------------

# No plural ``vendors``: that is as often first-party code about vendors
# (``llms/src/providers/vendors/openai.ts``) as a copied library.
_VENDORED_DIR_TOKENS = frozenset(
    {
        "vendor",
        "third_party",
        "thirdparty",
        "third-party",
        "node_modules",
        "bower_components",
        "site-packages",
    }
)
# Matched as the first segment, or as a native tree's library shelf
# (``src/native/external/<lib>/``). Anywhere else ``external/`` is as often a
# package that talks to external services (``inference/external/``) or a
# monorepo's own libraries as it is a copy of someone else's code.
_VENDORED_ROOT_TOKENS = frozenset({"external", "externals"})
_NATIVE_TREE = "native"
_MINIFIED_SUFFIXES = (".min.js", ".min.css", ".min.mjs")


def _is_vendored_path(lowered_name: str, dirs: list[str]) -> bool:
    if any(d in _VENDORED_DIR_TOKENS for d in dirs):
        return True
    if dirs and dirs[0] in _VENDORED_ROOT_TOKENS:
        return True
    # ``native/external/<lib>/...``: the library directory must be there too.
    if any(
        d == _NATIVE_TREE and dirs[i + 1] in _VENDORED_ROOT_TOKENS for i, d in enumerate(dirs[:-2])
    ):
        return True
    return lowered_name.endswith(_MINIFIED_SUFFIXES)


# A copied library is recognisable by its header only in the directories a
# site serves assets from. Anywhere else a license header is far more often
# the repository's own.
# ``min/`` is a minified distribution tree (Monaco ships as ``min/vs/...``); the
# header rule below keeps a first-party ``src/min/`` out.
_ASSET_DIR_TOKENS = frozenset({"docs", "doc", "static", "assets", "public", "_static", "min"})
_HEADER_LINES = 20
_LICENSE_RE = re.compile(
    r"copyright|\(c\)|©|@license|licen[cs]ed\s+under|released\s+under|\bMIT\b",
    re.IGNORECASE,
)
# What says the header names a project and its release, rather than an owner:
# a preserved banner, a license tag, or "<name> v1.2" / "<name>.js 0.10.5".
_BANNER_RE = re.compile(
    r"/\*!|@license|@preserve|\b[A-Za-z][\w.\-]*\s+v?\d+\.\d+(?:\.\d+)?\b"
)


def _comment_lines(header: str) -> list[str]:
    lines: list[str] = []
    for raw in header.splitlines()[:_HEADER_LINES]:
        text = _comment_text(raw.strip(), False)
        if text is not None:
            lines.append(text)
    return lines


def _squash(text: str) -> str:
    """Lowercase alphanumerics only, so ``my-lib`` and ``MyLib`` compare equal."""
    return re.sub(r"[^0-9a-z]", "", text.lower())


def _third_party_header(header: str, project: str | None) -> bool:
    """Whether the leading comments carry another project's license banner.

    Conservative on purpose: it needs a license or copyright line **and** a
    versioned or preserved banner, both in comments, and the banner must not
    name *project* when the caller knows it. A repository's own
    ``Copyright (c) 2024 Acme`` header has no release banner, so it stays.
    """
    comments = "\n".join(_comment_lines(header))
    # The comment prefix is stripped from *comments*, so a preserved ``/*!``
    # opener is read from the raw head.
    banner = _BANNER_RE.search(comments) or header.lstrip().startswith("/*!")
    if not comments or not _LICENSE_RE.search(comments) or not banner:
        return False
    return not (project and _squash(project) in _squash(comments))


# --------------------------------------------------------------------------
# Build
# --------------------------------------------------------------------------

# Build files, by type: what a build tool reads to configure, compile, package
# or run the project. A build tool loads each by its name, nothing imports one,
# and none ships, in whatever directory it sits. Exact names, spelled as the
# tool spells them (Bazel's ``BUILD`` is not a ``build`` script), by ecosystem.
_BUILD_FILE_NAMES = frozenset(
    {
        # Gradle, Maven, sbt, Mill and their wrappers
        "build.gradle",
        "build.gradle.kts",
        "settings.gradle",
        "settings.gradle.kts",
        "gradlew",
        "gradlew.bat",
        "pom.xml",
        "mvnw",
        "mvnw.cmd",
        "build.sbt",
        "build.sc",
        "build.mill",
        # CMake, Make, Autotools, Meson, SCons, Premake, xmake, Zig, Just
        "CMakeLists.txt",
        "Makefile",
        "makefile",
        "GNUmakefile",
        "Makefile.am",
        "Makefile.in",
        "configure.ac",
        "configure.in",
        "meson.build",
        "meson_options.txt",
        "meson.options",
        "SConstruct",
        "SConscript",
        "premake4.lua",
        "premake5.lua",
        "xmake.lua",
        "build.zig",
        "Justfile",
        "justfile",
        # Bazel, Buck
        "BUILD",
        "BUILD.bazel",
        "WORKSPACE",
        "WORKSPACE.bazel",
        "MODULE.bazel",
        "BUCK",
        # Cargo, SwiftPM, Mage, Mix, Leiningen, tools.build, Perl, Conan, nox
        "Cargo.toml",
        "Package.swift",
        "magefile.go",
        "mix.exs",
        "project.clj",
        "build.clj",
        "Makefile.PL",
        "Build.PL",
        "conanfile.py",
        "noxfile.py",
        # Ruby and JS task runners
        "Rakefile",
        "Gruntfile.js",
        "Gruntfile.coffee",
    }
)
# Suffixes that only a build file carries: Gradle scripts and precompiled
# script plugins, CMake modules, Make includes, Starlark, MSBuild imports
# (``Directory.Build.props``), package specs.
_BUILD_SUFFIXES = (
    ".gradle",
    ".gradle.kts",
    ".cmake",
    ".mk",
    ".bzl",
    ".props",
    ".targets",
    ".gemspec",
    ".podspec",
    # Cake (C# make): ``build.cake`` and its loaded ``*.cake`` scripts
    ".cake",
    ".rockspec",
)
# Bundler configs and gulp files, any extension a JS tool's config takes.
_BUILD_NAME_RE = re.compile(
    r"^(?:gulpfile|(?:webpack|vite|rollup|rolldown|rspack|esbuild|tsup)\.config(?:\.[\w-]+)*)"
    r"\.[cm]?[jt]s$"
)
# Names a build tool reads only at the root: a nested ``setup.py`` is as often
# a module (``homeassistant/setup.py`` sets up integrations).
_BUILD_ROOT_NAMES = frozenset({"setup.py"})
# Cargo runs ``build.rs`` from a crate root; directly in ``src/`` it is a
# module (``mod build;``). A crate root can sit under ``src/`` too
# (``src/bootstrap/build.rs`` in rust-lang/rust), so as a dead-code root every
# ``build.rs`` not directly in ``src/`` counts: a module there is reached by
# its ``mod`` edge anyway. As an origin, which hides code from fix lists, only
# one with no ``src/`` above it counts (``cli/src/commands/build.rs`` is a
# module).
_CRATE_ROOT_NAMES = frozenset({"build.rs"})
_SOURCE_DIR = "src"


def _is_build_name(name: str, dirs: list[str], *, as_origin: bool = False) -> bool:
    lowered = name.lower()
    return (
        name in _BUILD_FILE_NAMES
        or lowered.endswith(_BUILD_SUFFIXES)
        or bool(_BUILD_NAME_RE.match(lowered))
        or (not dirs and name in _BUILD_ROOT_NAMES)
        or (name in _CRATE_ROOT_NAMES and _at_crate_root(dirs, as_origin=as_origin))
    )


def _at_crate_root(dirs: list[str], *, as_origin: bool) -> bool:
    return _SOURCE_DIR not in dirs if as_origin else dirs[-1:] != [_SOURCE_DIR]


@lru_cache(maxsize=65536)
def is_build_file(path: str) -> bool:
    """Whether *path* is a build file: a build tool runs it, nothing imports it.

    Decided by the file's type alone, so it holds under ``vendor/`` or a test
    tree too. Dead code reads this as a root: such a file is never unreachable.
    """
    split = _split(path)
    return split is not None and _is_build_name(split[1], split[2])


# --------------------------------------------------------------------------
# Docs, examples, tooling
# --------------------------------------------------------------------------

# Docs roots count at any depth. Docs are the plural and FastAPI's ``docs_src``
# only: a singular ``doc/`` is as often a shipped package (cobra's ``doc``
# generates man pages) as a documentation tree.
_DOCS_ROOT_TOKENS = frozenset({"docs", "docs_src"})
# Examples as ``support_paths`` reads them, less the benchmark harnesses, which
# run the system (tooling below). Unlike ``support_paths`` these count only as
# the first segment or directly under a docs root: ``src/pkg/examples/`` is
# as often shipped code (an example registry, a runner) as a sample.
_EXAMPLE_TOKENS = EXAMPLE_DIR_TOKENS - {"bench", "benches", "benchmarks"}
_TUTORIAL_PREFIX = "tutorial"


def _is_example_dir(segment: str) -> bool:
    return segment in _EXAMPLE_TOKENS or segment.startswith(_TUTORIAL_PREFIX)


def _is_docs_example(dirs: list[str]) -> bool:
    # Anything under a docs root already counts, examples beneath it included.
    return any(d in _DOCS_ROOT_TOKENS for d in dirs) or bool(dirs and _is_example_dir(dirs[0]))


# No ``/cli/`` rule: a CLI's source ships and its findings are real work (only
# performance treats a CLI loop as off the request path, in
# ``perf/causal.execution_context``). Migrations join: they run once at deploy
# time and are append-only.
_TOOLING_DIR_TOKENS = frozenset(
    {
        ".github",
        "bench",
        "benches",
        "benchmarks",
        "build",
        "devtools",
        "scripts",
        "tooling",
        "tools",
        "migrations",
    }
)
# Build logic kept as its own Gradle build at the repository root. Root only:
# deeper, a ``build-tools`` package is as likely the product of a repository
# that ships build tooling.
_TOOLING_ROOT_DIRS = frozenset(
    {"buildsrc", "build-logic", "build-conventions", "build-tools", "build-tools-internal"}
)
# Schema migrations: a ``migrations/`` directory (above), or adjacent
# directories where neither name does alone. Rails keeps them in
# ``db/migrate``, Alembic in ``alembic/versions``; a bare ``versions/`` is too
# common (API versions) to class on its own. Ceiling: an Alembic script
# directory with another name is recognised only by its sibling ``env.py``,
# which a path-only classifier cannot see.
_MIGRATION_DIR = "migrations"
_MIGRATION_DIR_PAIRS = frozenset({("db", "migrate"), ("alembic", "versions")})
_TOOLING_ROOT_NAMES = frozenset({"fabfile.py"})
# Lint, test and transpiler configs. Bundler configs are build files (above).
_TOOLING_NAME_RE = re.compile(
    r"^(?:eslint\.config|jest\.config|vitest\.config|babel\.config|karma\.conf)\.[cm]?[jt]s$"
)


def _header_text(text: str | bytes | None) -> str:
    if text is None:
        return ""
    if isinstance(text, bytes):
        # Twenty lines of a hand-written file fit in 4 KB; a minified bundle
        # has no newlines, and its first 4 KB says as much as the rest.
        return text[:4096].decode("utf-8", errors="ignore")
    return text[:4096]


def _split(path: str) -> tuple[str, str, list[str]] | None:
    normalized = path.replace("\\", "/")
    parts = PurePosixPath(normalized).parts
    if not parts:
        return None
    return normalized, parts[-1], [p.lower() for p in parts[:-1]]


def _is_generated_path(name: str, dirs: list[str]) -> bool:
    return (
        _is_generated_name(name)
        or any(d in _GENERATED_DIR_TOKENS for d in dirs)
        or any(
            d == _GENERATED_BUILD_DIR and i and dirs[i - 1] in _BUILD_OUTPUT_PARENTS
            for i, d in enumerate(dirs)
        )
    )


@lru_cache(maxsize=65536)
def is_vendored_or_generated_path(path: str) -> bool:
    """Whether the path alone marks code nobody here maintains by hand.

    For callers with no file content, such as the dead-code passes: a copied
    library or a generator's output is never this repository's dead code.
    """
    split = _split(path)
    if split is None:
        return False
    _, name, dirs = split
    return _is_generated_path(name, dirs) or _is_vendored_path(name.lower(), dirs)


def _is_migration_dir(dirs: list[str]) -> bool:
    return _MIGRATION_DIR in dirs or any(pair in _MIGRATION_DIR_PAIRS for pair in pairwise(dirs))


def is_migration_path(path: str) -> bool:
    """Whether *path* is a schema migration: generated once, append-only, and
    meant to stay self-contained, so no shared helper or split belongs in it."""
    split = _split(path)
    return split is not None and _is_migration_dir(split[2])


def _is_tooling(name: str, dirs: list[str]) -> bool:
    return (
        any(d in _TOOLING_DIR_TOKENS for d in dirs)
        or bool(dirs and dirs[0] in _TOOLING_ROOT_DIRS)
        or _is_migration_dir(dirs)
        or (not dirs and name in _TOOLING_ROOT_NAMES)
        or bool(_TOOLING_NAME_RE.match(name.lower()))
    )


def code_origin(
    path: str,
    text: str | bytes | None = None,
    *,
    is_test: bool | None = None,
    project: str | None = None,
) -> CodeOrigin:
    """The one origin of the file at repo-relative *path*.

    *text* is the file's content, or just its head; only its first 4 KB are
    read. Without it the content rules (generated banner, reference-assembly
    stub, third-party license header) cannot fire and the answer rests on the
    path.

    *is_test* is the flag ingestion stored, when the caller has it. ``None``
    derives it from the path with the shared test classifier.

    *project* is the repository's name, so its own release banner is not
    taken for someone else's.
    """
    split = _split(path)
    if split is None:
        return "production"
    normalized, name, dirs = split
    header = _header_text(text)

    if _is_generated_path(name, dirs) or (
        header and (_declares_generated(name, header) or _is_reference_stub(name, dirs, header))
    ):
        return "generated"
    if _is_vendored_path(name.lower(), dirs) or (
        header
        and any(d in _ASSET_DIR_TOKENS for d in dirs)
        and _third_party_header(header, project)
    ):
        return "vendored"
    return _maintained_origin(normalized, name, dirs, is_test)


def _maintained_origin(
    normalized: str, name: str, dirs: list[str], is_test: bool | None
) -> CodeOrigin:
    """The origin of code this repository maintains: build, test, docs or
    examples, tooling, or production, in that precedence."""
    if _is_build_name(name, dirs, as_origin=True):
        return "build"
    if is_test if is_test is not None else is_test_related_path(normalized):
        return "test"
    if _is_docs_example(dirs):
        return "docs_example"
    if _is_tooling(name, dirs):
        return "tooling"
    return "production"


@lru_cache(maxsize=65536)
def path_origin(path: str) -> CodeOrigin:
    """:func:`code_origin` from the path alone, memoised.

    For callers holding no file content and no stored origin. A caller holding
    the stored ``code_origin`` reads that instead: it also saw the file's head.
    """
    return code_origin(path)


def ship_rank(path: str) -> int:
    """Sort key for ranked lists: product code 0, other non-test code 1, tests 2.

    A build script, a tool or a copied library can carry a real finding, but it
    never leads a list of things to fix ahead of the code that ships.
    """
    origin = path_origin(path)
    return 0 if origin == "production" else 2 if origin == "test" else 1
