"""Typed identifiers for graph and architecture nodes.

Every layer of this codebase writes node ids as strings with a short prefix
(``file:``, ``external:``, ``pkg:``, ``cmp:``…) and then takes them apart again
with hand-written ``split``/``startswith``/``removeprefix`` calls. That works
until two separators meet: a component id built as ``cmp:<path>::root`` puts a
``::`` — which everywhere else means "symbol inside a file" — inside a
``:``-prefixed id, and every reader that splits on ``::`` first gets it wrong.

This module is the one place that knows the spelling. :func:`parse` turns a
raw id into a typed value, :func:`render` turns it back, and the two are exact
inverses. Two rules keep them that way:

* **The prefix is matched against a fixed table, and it is matched first.** An
  unknown prefix is not a kind — ``C:\\src\\main.py`` is a Windows path, not a
  ``C`` node — so anything unrecognised parses as a file.
* **``::`` separates a file from a symbol, but only in an id with no prefix.**
  Inside a prefixed id it is ordinary data: Rust import resolution really emits
  ``external:serde::Deserialize``. :func:`render` raises only for the two
  unprefixed forms, where a separator genuinely has no unambiguous spelling.

Pure and dependency-free: no database, no filesystem, no imports from the rest
of the package, so it is safe to use from ingestion, the server and the CLI
alike.
"""

from __future__ import annotations

from dataclasses import dataclass

#: Separator between a file path and a symbol name. Reserved: no other id
#: kind may contain it.
SYMBOL_SEP = "::"

#: Separator between a component path and its synthetic root-bucket marker.
#: Deliberately not ``::`` — the old ``cmp:<path>::root`` spelling collided
#: with the symbol separator, so any reader splitting on ``::`` first saw a
#: file called ``cmp:<path>`` with a symbol called ``root``.
#:
#: Reserved at the end of a component path, the same way ``::`` is reserved.
#: Note ``#`` also delimits a URL fragment: an id put in a URL unencoded
#: truncates here. Nothing does that today.
_ROOT_MARKER = "#root"


@dataclass(frozen=True)
class FileId:
    """A source file, keyed on its repo-relative POSIX path."""

    path: str


@dataclass(frozen=True)
class KgFileId:
    """A file as spelled in the knowledge-graph artifact (``file:a.py``).

    The artifact prefixes file ids; the dependency graph does not. Keeping
    them as two types means a conversion between the two surfaces has to be
    written out, instead of a prefix silently appearing or vanishing.
    """

    path: str


@dataclass(frozen=True)
class SymbolId:
    """A named symbol inside a file (``path::Name``)."""

    path: str
    name: str


@dataclass(frozen=True)
class ExternalId:
    """A third-party or unresolvable import (``external:react``).

    ``name`` may itself contain colons — ``external:pub:http`` is a real Dart
    id — so only the first colon separates the prefix.
    """

    name: str


@dataclass(frozen=True)
class FrameworkId:
    """A synthetic node standing in for a framework's own code.

    Distinct from :class:`ExternalId` because it is generated by the framework
    edge passes rather than resolved from an import, and because the checks
    that special-case third-party code have historically looked for
    ``external:`` only and missed these entirely.
    """

    name: str


@dataclass(frozen=True)
class SystemId:
    """The C4 software system standing for the repository itself."""

    repo: str


@dataclass(frozen=True)
class PersonId:
    """A C4 actor, keyed on the kind of user it represents."""

    kind: str


@dataclass(frozen=True)
class ContainerId:
    """A C4 container — a workspace package or top-level directory."""

    path: str


@dataclass(frozen=True)
class ComponentId:
    """A C4 component — a directory inside a container.

    ``is_root_bucket`` marks the synthetic group holding files that sit at the
    container root. It is a field rather than a suffix glued onto ``path`` so
    the root bucket and the container share one path and nothing has to parse
    a marker back out of the string.
    """

    path: str
    is_root_bucket: bool = False


@dataclass(frozen=True)
class ExternalSystemId:
    """An external dependency as shown in a C4 view (``ext:react``).

    Separate from :class:`ExternalId`: that one names a node in the dependency
    graph, this one names a box in a diagram, and several graph nodes collapse
    into one box.
    """

    name: str


NodeId = (
    FileId
    | KgFileId
    | SymbolId
    | ExternalId
    | FrameworkId
    | SystemId
    | PersonId
    | ContainerId
    | ComponentId
    | ExternalSystemId
)

#: Prefix → constructor. Order does not matter: a raw id is split on its first
#: colon and the head looked up here, so no prefix can shadow another.
_BY_PREFIX: dict[str, type] = {
    "file": KgFileId,
    "external": ExternalId,
    "framework": FrameworkId,
    "sys": SystemId,
    "person": PersonId,
    "pkg": ContainerId,
    "cmp": ComponentId,
    "ext": ExternalSystemId,
}

_PREFIX_BY_TYPE: dict[type, str] = {v: k for k, v in _BY_PREFIX.items()}


class InvalidNodeIdError(ValueError):
    """Raised when a value cannot be rendered as an unambiguous id."""


def _reject_separator(kind: str, value: str) -> None:
    if SYMBOL_SEP in value:
        raise InvalidNodeIdError(
            f"{kind} contains the reserved symbol separator {SYMBOL_SEP!r}: {value!r}. "
            f"Only a symbol id may contain it."
        )


def render(node: NodeId) -> str:
    """Render a typed id back to its string form.

    Raises :class:`InvalidNodeIdError` rather than emitting a string that would
    parse back as a different kind — a file genuinely named ``a::b.py`` is
    legal on disk and has no unambiguous spelling here, and silently
    mis-parsing it later is worse than failing now.

    Only the *unprefixed* forms can hit that. A prefixed id is read prefix-first
    (see :func:`parse`), so a separator inside one is just part of the value and
    survives the round trip untouched.
    """
    if isinstance(node, SymbolId):
        # Only the path is at risk: ``parse`` splits on the FIRST separator, so
        # the name keeps any further ones. Rust and C++ symbol names need that.
        _reject_separator("symbol path", node.path)
        return f"{node.path}{SYMBOL_SEP}{node.name}"

    if isinstance(node, FileId):
        _reject_separator("file path", node.path)
        return node.path

    if isinstance(node, ComponentId):
        if node.path.endswith(_ROOT_MARKER):
            # ``cmp:packages/foo#root`` already spells the root bucket of
            # ``packages/foo``, so a directory genuinely named ``foo#root``
            # has no distinct spelling. Same trap as the symbol separator,
            # same answer: fail here rather than mis-parse later.
            raise InvalidNodeIdError(
                f"component path ends in the reserved root marker {_ROOT_MARKER!r}: "
                f"{node.path!r}"
            )
        marker = _ROOT_MARKER if node.is_root_bucket else ""
        return f"cmp:{node.path}{marker}"

    prefix = _PREFIX_BY_TYPE.get(type(node))
    if prefix is None:
        raise InvalidNodeIdError(f"not a node id: {node!r}")
    # Every remaining variant carries exactly one string field.
    (value,) = vars(node).values()
    return f"{prefix}:{value}"


def parse(raw: str) -> NodeId:
    """Parse a raw node id.

    Anything without a known prefix is a file path, which is what an
    unprefixed graph node id means and what keeps Windows paths
    (``C:\\src\\main.py``) from being read as a ``C`` node.

    The prefix is looked up **before** the symbol separator is considered.
    Testing the separator first made ``external:serde::Deserialize`` — the
    shape Rust import resolution emits for every crate — read as a symbol
    inside a file called ``external:serde``, so every check asking "is this
    third-party code?" answered no and the crate was treated as one of the
    repository's own files.
    """
    prefix, sep, rest = raw.partition(":")
    ctor = _BY_PREFIX.get(prefix) if sep else None
    if ctor is not None:
        if ctor is ComponentId:
            if rest.endswith(_ROOT_MARKER):
                return ComponentId(path=rest[: -len(_ROOT_MARKER)], is_root_bucket=True)
            return ComponentId(path=rest)
        return ctor(rest)  # type: ignore[call-arg]

    if SYMBOL_SEP in raw:
        path, _, name = raw.partition(SYMBOL_SEP)
        return SymbolId(path=path, name=name)
    return FileId(path=raw)


def is_external(raw: str) -> bool:
    """True if *raw* names code we do not own.

    Covers both ``external:`` and ``framework:``. Written once because the
    hand-rolled checks scattered around the tree test for ``external:`` alone
    and so miss every framework node.
    """
    return isinstance(parse(raw), ExternalId | FrameworkId)


def file_path_of(raw: str) -> str | None:
    """The file path *raw* refers to, or ``None`` if it names no file.

    A symbol resolves to the file that holds it; a file resolves to itself;
    everything else is not a file.
    """
    node = parse(raw)
    if isinstance(node, FileId | KgFileId | SymbolId):
        return node.path
    return None
