"""Linear, interpretable change-risk model.

Scores a :class:`ChangeFeatures` vector to a 0-10 change-risk plus a fully
attributable per-feature breakdown. The model is a plain L2-logistic over
standardized, log-compressed change features — the same per-finding-attributable
contract the file health score holds: the logit is a linear sum of per-feature
contributions, so each feature's push on the risk is exact and explainable. No
LLM, no network, no blame at runtime — only learned constants ship.

Constants are calibrated offline (``repowise-bench/health-defect/
jit_calibration.py``: AG-SZZ bug-inducing commits as labels, time-ordered
evaluation, right-censoring gap, leave-one-repo-out vs the churn-only baseline)
and pasted into ``_CONSTANTS`` below. Regenerate them there if the corpus moves.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

from .features import ChangeFeatures

# Calibrated offline (2026-05-30) on a 7-repo, 5-language slice of the corpus
# (clap, pydantic, fd, gin, fastify, bat, chi; AG-SZZ bug-inducing commits as
# labels, gap_days=120 right-censoring, pooled L2-logistic over the genuinely
# runtime-available features — age_days is excluded as a label-availability
# artifact). Generated by repowise-bench/health-defect/jit_calibration.py.
# Generalization (leave-one-repo-out pooled OOF, n=4102, 662 inducing): model
# AUC 0.772 vs churn-only baseline 0.766 (Δ +0.0068 [95% CI -0.0003, +0.0131]) —
# competitive with churn corpus-wide and stronger on some repos (clap +0.053
# time-split). Diff size (la) dominates, with entropy risky (+) and author
# experience protective (-), both literature-consistent; the small negative
# nf/nd/ns coefficients are collinearity with la (size), kept as fit. Order
# matters: features / log1p / mean / std / coef are parallel arrays.
_CONSTANTS: dict[str, object] = {
    "features": ["la", "ld", "nf", "nd", "ns", "entropy", "exp"],
    "log1p": [True, True, True, True, True, False, True],
    "mean": [2.443, 1.723, 1.006, 0.795, 0.806, 0.537, 3.011],
    "std": [1.414, 1.380, 0.465, 0.237, 0.285, 0.776, 2.270],
    "coef": [1.1241, 0.0151, -0.1103, -0.0310, -0.0672, 0.1483, -0.0702],
    "intercept": -0.3797,
}

# Human-readable driver labels, keyed by whether the feature is ABOVE its
# baseline value — (above-baseline phrase, below-baseline phrase). Each label
# compares the feature to *the model's baseline commit* (the calibration-corpus
# mean), NOT to this repo — so the wording is deliberately neutral and relative
# ("more / fewer ... than baseline"), never an absolute verdict like "large".
# The signed contribution + colour carry the risk direction, so a collinear
# coefficient sign never makes a risk-lowering feature read like a warning. The
# shared anchor phrase ("than the model's baseline commit") is stated once by the
# surface that renders these, so it is omitted from every individual label.
_FEATURE_LABELS: dict[str, tuple[str, str]] = {
    "la": ("more lines added than baseline", "fewer lines added than baseline"),
    "ld": ("more lines deleted than baseline", "fewer lines deleted than baseline"),
    "nf": ("more files than baseline", "fewer files than baseline"),
    "nd": ("more directories than baseline", "fewer directories than baseline"),
    "ns": ("more subsystems than baseline", "fewer subsystems than baseline"),
    "entropy": ("more scattered than baseline", "more focused than baseline"),
    "exp": ("more experienced author than baseline", "less familiar author than baseline"),
}


@dataclass
class RiskDriver:
    """One feature's contribution to the change-risk logit."""

    feature: str
    value: float  # raw feature value
    contribution: float  # signed push on the logit (coef * standardized value)
    label: str  # human-readable explanation


@dataclass
class ChangeRisk:
    """Result of scoring a change."""

    score: float  # 0-10 (10 * predicted probability)
    probability: float  # calibrated logistic probability
    level: str  # "low" | "moderate" | "high"
    drivers: list[RiskDriver] = field(default_factory=list)
    features: ChangeFeatures | None = None

    @property
    def top_drivers(self) -> list[RiskDriver]:
        """Drivers sorted by absolute contribution (strongest first)."""
        return sorted(self.drivers, key=lambda d: -abs(d.contribution))


def _sigmoid(z: float) -> float:
    if z >= 0:
        return 1.0 / (1.0 + math.exp(-z))
    e = math.exp(z)
    return e / (1.0 + e)


def _level(score: float) -> str:
    if score >= 7.0:
        return "high"
    if score >= 4.0:
        return "moderate"
    return "low"


def score_change(features: ChangeFeatures) -> ChangeRisk:
    """Score a :class:`ChangeFeatures` vector → :class:`ChangeRisk`.

    Linear and attributable: ``logit = intercept + Σ coef_i · z_i`` where
    ``z_i`` is the standardized (optionally log1p'd) feature, and each
    ``coef_i · z_i`` is reported as a :class:`RiskDriver`.
    """
    cols: list[str] = _CONSTANTS["features"]  # type: ignore[assignment]
    log1p: list[bool] = _CONSTANTS["log1p"]  # type: ignore[assignment]
    mean: list[float] = _CONSTANTS["mean"]  # type: ignore[assignment]
    std: list[float] = _CONSTANTS["std"]  # type: ignore[assignment]
    coef: list[float] = _CONSTANTS["coef"]  # type: ignore[assignment]
    intercept: float = float(_CONSTANTS["intercept"])  # type: ignore[arg-type]

    logit = intercept
    drivers: list[RiskDriver] = []
    for i, name in enumerate(cols):
        raw = getattr(features, name)
        if raw is None:
            # Unknown feature (e.g. author experience on a diff-only caller):
            # contribute nothing rather than impute, and say so.
            drivers.append(
                RiskDriver(
                    feature=name,
                    value=float("nan"),
                    contribution=0.0,
                    label=f"{name} (unknown)",
                )
            )
            continue
        raw = float(raw)
        x = math.log1p(raw) if log1p[i] else raw
        s = std[i] if std[i] else 1.0
        z = (x - mean[i]) / s
        contribution = coef[i] * z
        logit += contribution
        above, below = _FEATURE_LABELS.get(name, (name, name))
        # Label describes the feature's STATE (above/below typical); the signed
        # contribution carries the risk direction.
        drivers.append(
            RiskDriver(
                feature=name,
                value=raw,
                contribution=contribution,
                label=above if x >= mean[i] else below,
            )
        )

    prob = _sigmoid(logit)
    score = round(10.0 * prob, 1)
    return ChangeRisk(
        score=score,
        probability=prob,
        level=_level(score),
        drivers=drivers,
        features=features,
    )
