"""Linear, interpretable change-risk model.

Scores a :class:`ChangeFeatures` vector to a 0-10 change-risk plus a fully
attributable per-feature breakdown. The model is a plain L2-logistic over
standardized, log-compressed change features — the same per-finding-attributable
contract the file health score holds: the logit is a linear sum of per-feature
contributions, so each feature's push on the risk is exact and explainable. No
LLM, no network, no blame at runtime — only learned constants ship.

Constants are calibrated offline (``repowise-bench/health-defect/
jit_calibration.py``: AG-SZZ bug-inducing commits as labels, time-ordered
evaluation, right-censoring gap, leave-one-repo-out vs the churn-only baseline)
and pasted into ``_CONSTANTS`` below. Regenerate them there if the corpus moves.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

from ..risk_semantics import (
    ABSOLUTE_CHANGE_SCORE_HIGH,
    ABSOLUTE_CHANGE_SCORE_MODERATE,
    CHANGE_RISK_SCORE_MEASURES,
    CHANGE_RISK_SCORE_UNIT,
)
from .features import ChangeFeatures

SCORE_MEASURES = CHANGE_RISK_SCORE_MEASURES
SCORE_UNIT = CHANGE_RISK_SCORE_UNIT

# Calibrated offline (2026-05-30) on a 7-repo, 5-language slice of the corpus
# (clap, pydantic, fd, gin, fastify, bat, chi; AG-SZZ bug-inducing commits as
# labels, gap_days=120 right-censoring, pooled L2-logistic over the genuinely
# runtime-available features — age_days is excluded as a label-availability
# artifact). Generated by repowise-bench/health-defect/jit_calibration.py.
# Generalization (leave-one-repo-out pooled OOF, n=4102, 662 inducing): model
# AUC 0.772 vs churn-only baseline 0.766 (Δ +0.0068 [95% CI -0.0003, +0.0131]).
# Diff size (la) dominates, with entropy risky (+) and author experience
# protective (-), both literature-consistent; the small negative nf/nd/ns
# coefficients are collinearity with la (size), kept as fit. Order matters:
# features / log1p / mean / std / coef are parallel arrays.
#
# Kept unchanged deliberately. A PR-granularity refit adding two size-orthogonal
# features was measured and scored *worse*: pooled LOO AUC 0.769 against 0.776
# for this feature set and 0.780 for churn-only, with la alone matching or
# beating the fitted model in five of six repos. The SZZ labels are size-biased
# (a bigger commit writes more lines, so more of them get blamed later), so AUC
# against them rewards predicting size and cannot see a size-orthogonal signal.
# That is why the score is now reported as a diff-size statistic and the
# fix-history block carries what it cannot. See SCORE_MEASURES below.
_CONSTANTS: dict[str, object] = {
    "features": ["la", "ld", "nf", "nd", "ns", "entropy", "exp"],
    "log1p": [True, True, True, True, True, False, True],
    "mean": [2.443, 1.723, 1.006, 0.795, 0.806, 0.537, 3.011],
    "std": [1.414, 1.380, 0.465, 0.237, 0.285, 0.776, 2.270],
    "coef": [1.1241, 0.0151, -0.1103, -0.0310, -0.0672, 0.1483, -0.0702],
    "intercept": -0.3797,
}

# Human-readable driver labels, keyed by whether the feature is ABOVE its
# baseline value — (above-baseline phrase, below-baseline phrase). Each label
# compares the feature to *the model's baseline commit* (the calibration-corpus
# mean), NOT to this repo — so the wording is deliberately neutral and relative
# ("more / fewer ... than baseline"), never an absolute verdict like "large".
# The signed contribution + colour carry the model-output direction, so a
# collinear coefficient sign never makes a score-lowering feature a warning. The
# shared anchor phrase ("than the model's baseline commit") is stated once by the
# surface that renders these, so it is omitted from every individual label.
_FEATURE_LABELS: dict[str, tuple[str, str]] = {
    "la": ("more lines added than baseline", "fewer lines added than baseline"),
    "ld": ("more lines deleted than baseline", "fewer lines deleted than baseline"),
    "nf": ("more files than baseline", "fewer files than baseline"),
    "nd": ("more directories than baseline", "fewer directories than baseline"),
    "ns": ("more subsystems than baseline", "fewer subsystems than baseline"),
    "entropy": ("more scattered than baseline", "more focused than baseline"),
    "exp": ("more experienced author than baseline", "less familiar author than baseline"),
}


@dataclass
class RiskDriver:
    """One feature's contribution to the change-risk logit."""

    feature: str
    value: float | None  # raw feature value; None when the feature is unknown
    contribution: float  # signed push on the logit (coef * standardized value)
    label: str  # human-readable explanation


#: Features whose contribution is real but whose *explanation* is not.
#:
#: ``nf``/``nd``/``ns`` carry small negative coefficients that are collinearity
#: with ``la`` (size), not a finding that touching more files is safer. Reported
#: as drivers they contradict themselves: the label says "more directories than
#: baseline" while the colour says protective. They still enter the logit
#: exactly as fit — this hides an explanation we cannot stand behind, not a
#: number. A refit is the real fix.
_UNREPORTABLE_DRIVERS = frozenset({"nf", "nd", "ns"})


@dataclass
class ChangeRisk:
    """Result of scoring a change."""

    score: float  # 0-10 offline-calibrated model output; public supporting signal
    level: str  # absolute band; see _level
    drivers: list[RiskDriver] = field(default_factory=list)
    features: ChangeFeatures | None = None

    @property
    def top_drivers(self) -> list[RiskDriver]:
        """Reportable drivers, sorted by absolute contribution (strongest first).

        ``drivers`` holds the full attribution and always sums to the logit;
        this is the display subset, minus ``_UNREPORTABLE_DRIVERS``.
        """
        return sorted(
            (d for d in self.drivers if d.feature not in _UNREPORTABLE_DRIVERS),
            key=lambda d: -abs(d.contribution),
        )


def _sigmoid(z: float) -> float:
    if z >= 0:
        return 1.0 / (1.0 + math.exp(-z))
    e = math.exp(z)
    return e / (1.0 + e)


#: What the score actually measures is centralized in ``risk_semantics``.
#: Measured, not asserted: `la` (lines added) carries a coefficient 7.6x the next
#: largest, and scoring by `la` alone reproduces the full score to within
#: 0.12-0.16 points on every repo tried. Refitting at PR granularity with two
#: size-orthogonal features added made this worse, not better (`la` 18x the next
#: largest), because the SZZ labels the model is fit against are themselves
#: size-biased: a bigger commit writes more lines, so more of its lines get
#: blamed by a later fix. Ranking changes by lines-added alone beats the fitted
#: model on that benchmark. So the score is reported as what it demonstrably is —
#: a diff-size statistic — and ``fix_history`` carries the part that is not.


def _level(score: float) -> str:
    """Absolute model-score band — the fallback when no percentile is available.

    Portable only across repos whose typical commit resembles the calibration
    corpus (see :data:`SCORE_UNIT`). Surfaces lead with the repo-relative
    review priority and fall back to this only when the baseline sample is
    empty or too small to rank against.
    """
    if score >= ABSOLUTE_CHANGE_SCORE_HIGH:
        return "high"
    if score >= ABSOLUTE_CHANGE_SCORE_MODERATE:
        return "moderate"
    return "low"


def score_change(features: ChangeFeatures) -> ChangeRisk:
    """Score a :class:`ChangeFeatures` vector → :class:`ChangeRisk`.

    Linear and attributable: ``logit = intercept + Σ coef_i · z_i`` where
    ``z_i`` is the standardized (optionally log1p'd) feature, and each
    ``coef_i · z_i`` is reported as a :class:`RiskDriver`.
    """
    cols: list[str] = _CONSTANTS["features"]  # type: ignore[assignment]
    log1p: list[bool] = _CONSTANTS["log1p"]  # type: ignore[assignment]
    mean: list[float] = _CONSTANTS["mean"]  # type: ignore[assignment]
    std: list[float] = _CONSTANTS["std"]  # type: ignore[assignment]
    coef: list[float] = _CONSTANTS["coef"]  # type: ignore[assignment]
    intercept: float = float(_CONSTANTS["intercept"])  # type: ignore[arg-type]

    logit = intercept
    drivers: list[RiskDriver] = []
    for i, name in enumerate(cols):
        raw = getattr(features, name)
        if raw is None:
            # Unknown feature (e.g. author experience on a diff-only caller):
            # contribute nothing rather than impute, and say so. The value is
            # None, not NaN — NaN is not JSON, and every serializing boundary
            # would otherwise have to strip it back out one by one.
            drivers.append(
                RiskDriver(
                    feature=name,
                    value=None,
                    contribution=0.0,
                    label=f"{name} (unknown)",
                )
            )
            continue
        raw = float(raw)
        x = math.log1p(raw) if log1p[i] else raw
        s = std[i] if std[i] else 1.0
        z = (x - mean[i]) / s
        contribution = coef[i] * z
        logit += contribution
        above, below = _FEATURE_LABELS.get(name, (name, name))
        # Label describes the feature's STATE (above/below typical); the signed
        # contribution carries the model-output direction.
        drivers.append(
            RiskDriver(
                feature=name,
                value=raw,
                contribution=contribution,
                label=above if x >= mean[i] else below,
            )
        )

    score = round(10.0 * _sigmoid(logit), 1)
    return ChangeRisk(score=score, level=_level(score), drivers=drivers, features=features)
