"""Per-commit agent-provenance classification — deterministic, precision-first.

Labels a commit ``{agent, autonomy_tier, channel, confidence}`` from the
attribution channels available in **local git history** (identity fields,
message footers, ``Co-authored-by:`` trailers — no network, no API calls, no
LLM), in strip-resistance order:

  Tier 1 (near-autonomous — an agent service account authored the commit):
     * commit AUTHOR is a known agent bot account / service e-mail
       (``copilot-swe-agent[bot]``, ``devin-ai-integration[bot]``,
       ``cursoragent@cursor.com``, ...)
  Tier 2 (human-driven agent — the agent wrote the change):
     * commit-message footer (exact service phrases: "Generated with Claude
       Code", opencode, Codex) or the aider author-name suffix ``... (aider)``
     * a service identity as COMMITTER over a human author (the agent
       pushed/amended a human-driven change — deliberately NOT tier 1)
  Tier 3 (assisted — an agent contributed, a human authored):
     * ``Co-authored-by:`` trailer naming a known agent service identity
     * an ``Assisted-by:`` trailer naming a recognized agent (the Fedora /
       OpenInfra AI-attribution standard)

Three cross-cutting channels ride the same rule set:
  * a **git-ai authorship note** (``refs/notes/ai``, the git-ai standard) —
    an explicit, line-level attestation attached to the commit. Read out of
    band (see :mod:`git_commit_index`) and passed in pre-resolved as
    ``note_agent``; classified Tier 2 (``git_ai_note`` channel).
  * an **agent-trace record** (the vendor-neutral agent-trace standard,
    ``.agent-trace/traces.jsonl``) resolved to the commit by
    :class:`AgentTraceIndex` and passed in as ``trace_agent``; classified
    Tier 2 (``agent_trace`` channel).
  * a ``Generated-by:`` trailer (Apache's AI-attribution footer) naming a
    recognized agent — Tier 2 (``generated_by_trailer`` channel).

Precedence is tier order (1 > 2 > 3); first match wins. A commit with no
match is human (``None``). Every pattern is anchored to a *service identity*
(bot login, service e-mail, exact footer phrase) — never a bare name. A loose
name pattern is how a human contributor named "Devin" gets misclassified as
the Devin agent; a false "agent-authored" label on a human commit is worse
than a miss.

PR-level channels (bot PR author, agent branch prefixes, PR-body footers)
require the forge API and are intentionally out of scope here: squash merges
that strip commit trailers are therefore a known recall loss, not a precision
loss. ``confidence`` is carried per channel so future, weaker channels can be
filtered by consumers; every local channel is ``"high"``.

The default registry below is data, not code: repos can extend it from
``.repowise/config.yaml`` (see :func:`classifier_from_repo_config`) without
touching this module, e.g.::

    agent_provenance:
      service_emails:
        mybot@example.com: {agent: mybot, tier: 1}
      footer_patterns:
        - {pattern: "Generated by MyBot", agent: mybot}
      coauthor_patterns:
        - {pattern: "^co-authored-by: mybot <[^>]*@example\\.com>", agent: mybot}

Classification is pure in-memory regex over already-parsed commit records and
rides the existing commit-index walk — it adds no git subprocess and no I/O.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

import structlog

logger = structlog.get_logger(__name__)

__all__ = [
    "AgentProvenance",
    "AgentProvenanceClassifier",
    "AgentTraceIndex",
    "_agent_from_git_ai_note",
    "classifier_from_repo_config",
]


# ------------------------------------------------------------------ registry --

# Bot login (lowercase, without the ``[bot]`` suffix) → agent name, for
# ``<login>[bot]@users.noreply.github.com`` author/committer e-mails (GitHub's
# canonical bot identity, also re-injected on squash merges).
_BOT_LOGINS: dict[str, str] = {
    "copilot-swe-agent": "copilot",
    "copilot": "copilot",
    "devin-ai-integration": "devin",
    "cursor": "cursor",
    "cursoragent": "cursor",
    "google-labs-jules": "jules",
    "gemini-code-assist": "gemini",
    "codegen-sh": "codegen",
    "openhands-ai": "openhands",
    "sweep-ai": "sweep",
    "claude": "claude",
}

# Agent name/tool aliases → canonical label. Substring match (first hit wins),
# so ``GitHub Copilot`` → ``copilot`` and ``claude-code`` → ``claude``. Used to
# resolve free-text values in ``Assisted-by:`` / ``Generated-by:`` trailers and
# the ``agent_id.tool`` field of git-ai notes. ``chatgpt`` precedes ``gpt`` so
# the more specific token wins first.
_AGENT_ALIASES: list[tuple[str, str]] = [
    ("claude", "claude"),
    ("cursor", "cursor"),
    ("copilot", "copilot"),
    ("chatgpt", "chatgpt"),
    ("gpt", "chatgpt"),
    ("codex", "codex"),
    ("gemini", "gemini"),
    ("windsurf", "windsurf"),
    ("opencode", "opencode"),
    ("devin", "devin"),
    ("aider", "aider"),
    ("jules", "jules"),
    ("llama", "llama"),
]

# Exact service e-mails → (agent, tier) for commit identity fields.
_SERVICE_EMAILS: dict[str, tuple[str, int]] = {
    "cursoragent@cursor.com": ("cursor", 1),
    "devin-ai-integration[bot]@users.noreply.github.com": ("devin", 1),
    # Primarily Claude's co-author identity; as AUTHOR it is tier 1 like every
    # other service e-mail here.
    "noreply@anthropic.com": ("claude", 1),
}

# Agent-vendor e-mail domains → the exact agent identities each vendor emits.
# A domain alone is never enough — real humans work at these companies — so an
# identity here counts only when the LOCAL PART fully matches the vendor's
# allowlisted agent identity (anchored fullmatch, never a substring scan, and
# per vendor, never a flat token set): ``claude@anthropic.com`` and the
# ``claude-<model>`` slugs match; ``jane@anthropic.com``,
# ``jean-claude@anthropic.com`` and ``codex@anthropic.com`` never do.
_VENDOR_DOMAIN_LOCALS: dict[str, tuple[re.Pattern[str], str]] = {
    "anthropic.com": (re.compile(r"claude(?:-(?:opus|sonnet|haiku)(?:-[\w.]+)?)?"), "claude"),
    "openai.com": (re.compile(r"codex"), "codex"),
    "cursor.com": (re.compile(r"cursor(?:agent)?"), "cursor"),
    "devin.ai": (re.compile(r"devin"), "devin"),
}

# Commit-message footers → agent (exact service phrases only).
_FOOTER_PATTERNS: list[tuple[str, str]] = [
    (r"generated with \[?claude code\]?", "claude"),
    (r"generated with \[?opencode\]?", "opencode"),
    (r"generated with \[?(?:openai )?codex\]?", "codex"),
    (r"generated with \[?cursor\]?", "cursor"),
    (r"<!--\s*cursor\s*-->", "cursor"),
    (r"^\s*aider wrote this", "aider"),
]

# AI-attribution trailers (Fedora/OpenInfra ``Assisted-by``, Apache
# ``Generated-by``). The trailer KEY is the anchor — a standardized AI marker —
# but the agent identity comes from the value, so these fire only when the
# value resolves to a recognized agent (``allow_slug=False``): a bare human
# name in a misused ``Assisted-by`` must never mint a phantom agent. Generated =
# agent wrote it (T2); Assisted = human wrote it, agent helped (T3).
_GENERATED_BY_RE = re.compile(r"^\s*generated-by:\s*(.+?)\s*$", re.IGNORECASE | re.MULTILINE)
_ASSISTED_BY_RE = re.compile(r"^\s*assisted-by:\s*(.+?)\s*$", re.IGNORECASE | re.MULTILINE)

# ``Co-authored-by:`` trailers → agent. Anchored to the trailer position AND
# the agent's service identity — a name alone is not enough (see module doc).
_COAUTHOR_PATTERNS: list[tuple[str, str]] = [
    (
        r"^co-authored-by:\s*claude(?:\s+(?:opus|sonnet|haiku)[^<]*)?\s*<[^>]*@anthropic\.com>",
        "claude",
    ),
    (r"^co-authored-by:\s*copilot\s*<\d+\+copilot@users\.noreply\.github\.com>", "copilot"),
    (
        r"^co-authored-by:\s*cursor(?:\s*agent)?\s*<(?:cursoragent@cursor\.com|[^>]*cursor[^>]*)>",
        "cursor",
    ),
    (r"^co-authored-by:\s*opencode\s*<", "opencode"),
    (r"^co-authored-by:\s*devin[^<]*<[^>]*devin-ai-integration[^>]*>", "devin"),
    (r"^co-authored-by:\s*aider[^<]*<[^>]*aider[^>]*>", "aider"),
]

_AIDER_NAME_RE = re.compile(r"\(aider\)\s*$")

# Any ``Co-authored-by:`` trailer's e-mail, for registry-based identity
# matching: agent service identities the explicit patterns above don't name
# (bot noreply logins, exact service e-mails, vendor-domain identities) are
# resolved through the same :meth:`AgentProvenanceClassifier._identity_match`
# registry — one list, no parallel patterns.
_COAUTHOR_EMAIL_RE = re.compile(r"^co-authored-by:[^<\n]*<([^>\s]+)>", re.IGNORECASE | re.MULTILINE)


def _normalize_agent_token(value: str, *, allow_slug: bool) -> str | None:
    """Resolve a free-text tool/agent name to a canonical label.

    Matches *value* against :data:`_AGENT_ALIASES` (substring, first hit wins).
    With ``allow_slug`` the unmatched remainder is slugified and returned (used
    for git-ai notes, whose ``refs/notes/ai`` ref is AI-specific by
    construction, so an unknown tool is still a genuine agent). Without it, an
    unrecognized value returns ``None`` — the precision-first path for
    free-text trailers where a bare human name must not become an agent.
    """
    v = (value or "").strip().lower()
    if not v:
        return None
    for needle, canon in _AGENT_ALIASES:
        if needle in v:
            return canon
    if not allow_slug:
        return None
    slug = re.sub(r"[^a-z0-9]+", "-", v).strip("-")
    return slug or None


def _agent_from_git_ai_note(note: str) -> str | None:
    """Resolve the dominant agent from a git-ai authorship note.

    A note (``refs/notes/ai``, git-ai standard v3.0.0) is
    ``<attestation>\\n---\\n<json metadata>``. We read
    ``sessions.<id>.agent_id.tool`` from the JSON metadata and return the tool
    owning the most sessions, normalized to our agent label. A tie between
    distinct tools returns ``None`` (ambiguous — precision-first; per-line
    dominance from the attestation section is the upgrade path). Any parse
    failure returns ``None``: a malformed note is never a signal.
    """
    if not note:
        return None
    try:
        lines = note.splitlines()
        div = max((i for i, ln in enumerate(lines) if ln.strip() == "---"), default=-1)
        if div < 0:
            return None
        data = json.loads("\n".join(lines[div + 1 :]))
        counts: dict[str, int] = {}
        for sess in (data.get("sessions") or {}).values():
            tool = ((sess or {}).get("agent_id") or {}).get("tool")
            agent = _normalize_agent_token(str(tool), allow_slug=True) if tool else None
            if agent:
                counts[agent] = counts.get(agent, 0) + 1
        if not counts:
            return None
        top = max(counts.values())
        leaders = [a for a, c in counts.items() if c == top]
        return leaders[0] if len(leaders) == 1 else None
    except Exception:
        return None


# Agent-trace records (the vendor-neutral agent-trace standard, v0.1.x): JSONL
# at ``.agent-trace/traces.jsonl``, the spec's reference-implementation storage
# location. The spec itself is storage-agnostic; revisit when the ecosystem
# settles on a git-notes ref.
_TRACE_FILE = ".agent-trace/traces.jsonl"
# A trace log is append-only and unbounded; past this size, skip it whole
# rather than stall the git index parsing it.
_TRACE_MAX_BYTES = 50 * 1024 * 1024
_TRACE_AI_CONTRIBUTORS = frozenset({"ai", "mixed"})


def _agent_from_trace_record(rec: object) -> tuple[str, str, frozenset[str]] | None:
    """Resolve one agent-trace record to ``(revision, agent, ai_paths)``.

    A record carries ``vcs.revision`` (the git sha at capture time), a
    record-level ``tool``, and per-file ``conversations`` whose ``contributor``
    says who wrote the ranges. Only ``ai`` / ``mixed`` contributors count.
    The agent label prefers ``tool.name`` (matching the tool-level labels the
    other channels produce) and falls back to the conversation's ``model_id``;
    both resolve with ``allow_slug=True`` because the ``.agent-trace/`` log is
    AI-specific by construction, same rationale as ``refs/notes/ai``. Multiple
    distinct agents in one record: the one touching the most files wins, a tie
    returns ``None`` (ambiguous, precision-first). Any malformed shape returns
    ``None``: a broken record is never a signal.
    """
    if not isinstance(rec, dict):
        return None
    try:
        revision = str((rec.get("vcs") or {}).get("revision") or "").strip().lower()
        if not revision:
            return None
        tool_agent = _normalize_agent_token(
            str((rec.get("tool") or {}).get("name") or ""), allow_slug=True
        )
        paths_by_agent: dict[str, set[str]] = {}
        for f in rec.get("files") or []:
            if not isinstance(f, dict):
                continue
            path = str(f.get("path") or "").strip().lstrip("/")
            if not path:
                continue
            for conv in f.get("conversations") or []:
                if not isinstance(conv, dict):
                    continue
                contributor = conv.get("contributor") or {}
                if str(contributor.get("type") or "").lower() not in _TRACE_AI_CONTRIBUTORS:
                    continue
                agent = tool_agent or _normalize_agent_token(
                    str(contributor.get("model_id") or ""), allow_slug=True
                )
                if agent:
                    paths_by_agent.setdefault(agent, set()).add(path)
        if not paths_by_agent:
            return None
        top = max(len(paths) for paths in paths_by_agent.values())
        leaders = [a for a, paths in paths_by_agent.items() if len(paths) == top]
        if len(leaders) != 1:
            return None
        return revision, leaders[0], frozenset(paths_by_agent[leaders[0]])
    except Exception:
        return None


class AgentTraceIndex:
    """Commit attribution from agent-trace records, loaded once per walk.

    ``resolve`` maps a commit to an agent when a record's ``vcs.revision``
    matches the commit itself (the record was written at or after the commit:
    confidence ``"high"``) or one of its parents (the record was written at
    edit time and the traced change landed in the child: confidence
    ``"medium"``). Both cases additionally require the record's file set to
    intersect the commit's changed paths; a revision match alone must not
    attribute an unrelated commit.
    """

    def __init__(self, records: list[tuple[str, str, frozenset[str]]] | None = None) -> None:
        self._by_revision: dict[str, list[tuple[str, frozenset[str]]]] = {}
        for revision, agent, paths in records or []:
            self._by_revision.setdefault(revision, []).append((agent, paths))

    def __bool__(self) -> bool:
        return bool(self._by_revision)

    @classmethod
    def load(cls, repo: object) -> AgentTraceIndex:
        """Read ``.agent-trace/traces.jsonl`` from *repo*'s working tree.

        A missing file (the common case) returns an empty index after a single
        stat call, so repos without traces pay nothing. Oversized files are
        skipped whole and malformed lines individually: a broken trace log
        must never take down the git index.
        """
        try:
            root = getattr(repo, "working_tree_dir", None)
            if not root or not isinstance(root, (str, Path)):
                return cls()
            path = Path(root) / _TRACE_FILE
            if not path.is_file():
                return cls()
            if path.stat().st_size > _TRACE_MAX_BYTES:
                logger.warning("agent_trace_file_too_large", path=str(path))
                return cls()
            text = path.read_text(encoding="utf-8", errors="replace")
        except Exception as exc:  # a trace read must never break the git index
            logger.warning("agent_trace_read_failed", error=str(exc))
            return cls()
        records: list[tuple[str, str, frozenset[str]]] = []
        for line in text.splitlines():
            if not line.strip():
                continue
            try:
                rec = json.loads(line)
            except ValueError:
                continue
            parsed = _agent_from_trace_record(rec)
            if parsed:
                records.append(parsed)
        return cls(records)

    def resolve(
        self, sha: str, parents: tuple[str, ...], changed_paths: set[str]
    ) -> tuple[str, str] | None:
        """Attribute one commit: ``(agent, confidence)`` or ``None``."""
        agent = self._match(sha, changed_paths)
        if agent:
            return agent, "high"
        for parent in parents:
            agent = self._match(parent, changed_paths)
            if agent:
                return agent, "medium"
        return None

    def _match(self, revision: str, changed_paths: set[str]) -> str | None:
        candidates = self._by_revision.get((revision or "").lower())
        if not candidates:
            return None
        # Weight each agent by how many of its traced files this commit
        # actually changed; the dominant agent wins, a tie is ambiguous.
        counts: dict[str, int] = {}
        for agent, paths in candidates:
            overlap = len(paths & changed_paths)
            if overlap:
                counts[agent] = counts.get(agent, 0) + overlap
        if not counts:
            return None
        top = max(counts.values())
        leaders = [a for a, c in counts.items() if c == top]
        return leaders[0] if len(leaders) == 1 else None


@dataclass(frozen=True)
class AgentProvenance:
    """One commit's agent attribution. ``agent is None`` means human."""

    agent: str | None = None
    autonomy_tier: int | None = None  # 1 near-autonomous · 2 human-driven · 3 assisted
    channel: str | None = None
    confidence: str | None = None  # "high" | "medium" (local channels: always high)


_HUMAN = AgentProvenance()


class AgentProvenanceClassifier:
    """Compiled pattern registry + the classification rule.

    Construct once per index run (compilation is the only non-trivial cost);
    :meth:`classify` is then a handful of anchored regex searches per commit.
    Extra patterns merge on top of the built-in registry; they never replace
    it (precision of the defaults is validated, user patterns are additive).
    """

    def __init__(
        self,
        *,
        extra_service_emails: dict[str, tuple[str, int]] | None = None,
        extra_footer_patterns: list[tuple[str, str]] | None = None,
        extra_coauthor_patterns: list[tuple[str, str]] | None = None,
    ) -> None:
        self._service_emails = {**_SERVICE_EMAILS, **(extra_service_emails or {})}
        # ``[bot]`` is optional: GitHub squash-merges authored by the Copilot
        # coding agent use ``<id>+Copilot@users.noreply.github.com`` (no
        # suffix). Safe because each login is a unique, vendor-owned GitHub
        # account — no human can register them.
        self._bot_email_re = re.compile(
            r"^(?:\d+\+)?("
            + "|".join(re.escape(b) for b in _BOT_LOGINS)
            + r")(?:\[bot\])?@users\.noreply\.github\.com$",
            re.IGNORECASE,
        )
        self._footers = [
            (re.compile(p, re.IGNORECASE | re.MULTILINE), agent)
            for p, agent in [*_FOOTER_PATTERNS, *(extra_footer_patterns or [])]
        ]
        self._coauthors = [
            (re.compile(p, re.IGNORECASE | re.MULTILINE), agent)
            for p, agent in [*_COAUTHOR_PATTERNS, *(extra_coauthor_patterns or [])]
        ]

    def _identity_match(self, email: str) -> tuple[str, int] | None:
        e = (email or "").strip().lower()
        if not e:
            return None
        hit = self._service_emails.get(e)
        if hit:
            return hit
        m = self._bot_email_re.match(e)
        if m:
            return (_BOT_LOGINS[m.group(1).lower()], 1)
        local, _, domain = e.partition("@")
        vendor = _VENDOR_DOMAIN_LOCALS.get(domain)
        if vendor and vendor[0].fullmatch(local):
            return (vendor[1], 1)
        return None

    def classify(
        self,
        author_name: str,
        author_email: str,
        committer_name: str,
        committer_email: str,
        message: str,
        note_agent: str | None = None,
        trace_agent: str | None = None,
        trace_confidence: str = "high",
    ) -> AgentProvenance:
        """Classify one commit from local metadata. *message* is the full
        commit message (subject + body) — trailers and footers live in the
        body, so passing the subject alone silently disables several channels.
        *note_agent* is the pre-resolved agent from this commit's git-ai
        authorship note (``refs/notes/ai``), or ``None`` when absent — read out
        of band by the caller so classification stays a pure function.
        *trace_agent* / *trace_confidence* are the pre-resolved result of
        :meth:`AgentTraceIndex.resolve` for this commit, same contract."""
        # T1 — agent service identity AUTHORED the commit.
        hit = self._identity_match(author_email)
        if hit:
            return AgentProvenance(hit[0], hit[1], "service_email", "high")
        # T2 — git-ai authorship note: an explicit line-level attestation on
        # this commit. Below T1 (a bot service account is more autonomous) but
        # above the message-derived channels.
        if note_agent:
            return AgentProvenance(note_agent, 2, "git_ai_note", "high")
        # T2 — agent-trace record resolved to this commit. Below the git-ai
        # note (a commit-attached attestation beats heuristic revision
        # mapping), above the message-derived channels.
        if trace_agent:
            return AgentProvenance(trace_agent, 2, "agent_trace", trace_confidence)
        # T2 — message footer / aider author-name suffix.
        for pat, agent in self._footers:
            if pat.search(message):
                return AgentProvenance(agent, 2, "message_footer", "high")
        if _AIDER_NAME_RE.search(author_name or ""):
            return AgentProvenance("aider", 2, "author_name_aider", "high")
        # T2 — ``Generated-by:`` AI-attribution trailer (agent generated it).
        m = _GENERATED_BY_RE.search(message)
        if m:
            agent = _normalize_agent_token(m.group(1), allow_slug=False)
            if agent:
                return AgentProvenance(agent, 2, "generated_by_trailer", "high")
        # T2 — service identity as COMMITTER over a human author: the agent
        # pushed/amended a human-driven change. Deliberately tier 2, not 1.
        hit = self._identity_match(committer_email)
        if hit:
            return AgentProvenance(hit[0], max(hit[1], 2), "service_committer", "high")
        # T3 — ``Assisted-by:`` AI-attribution trailer (human wrote it, agent
        # helped). Below the committer channel to keep tier order intact.
        m = _ASSISTED_BY_RE.search(message)
        if m:
            agent = _normalize_agent_token(m.group(1), allow_slug=False)
            if agent:
                return AgentProvenance(agent, 3, "assisted_by_trailer", "high")
        # T3 — co-author trailer naming an agent service identity.
        for pat, agent in self._coauthors:
            if pat.search(message):
                return AgentProvenance(agent, 3, "coauthor_trailer", "high")
        for m in _COAUTHOR_EMAIL_RE.finditer(message):
            hit = self._identity_match(m.group(1))
            if hit:
                return AgentProvenance(hit[0], 3, "coauthor_trailer", "high")
        return _HUMAN


def classifier_from_repo_config(repo_path: object) -> AgentProvenanceClassifier:
    """Build a classifier with any repo-local pattern extensions.

    Reads the optional ``agent_provenance`` block of ``.repowise/config.yaml``
    (see module docstring for the shape). Malformed entries are skipped with a
    warning — a broken user pattern must never take down the git index.
    """
    extra_emails: dict[str, tuple[str, int]] = {}
    extra_footers: list[tuple[str, str]] = []
    extra_coauthors: list[tuple[str, str]] = []
    try:
        from ...repo_config import load_repo_config

        block = load_repo_config(repo_path).get("agent_provenance") or {}  # type: ignore[arg-type]
        if isinstance(block, dict):
            for email, spec in (block.get("service_emails") or {}).items():
                if isinstance(spec, dict) and spec.get("agent"):
                    tier = max(1, min(3, int(spec.get("tier", 1))))
                    extra_emails[str(email).lower()] = (str(spec["agent"]), tier)
            for key, sink in (
                ("footer_patterns", extra_footers),
                ("coauthor_patterns", extra_coauthors),
            ):
                for entry in block.get(key) or []:
                    if not (
                        isinstance(entry, dict) and entry.get("pattern") and entry.get("agent")
                    ):
                        continue
                    try:
                        re.compile(entry["pattern"])
                    except re.error as exc:
                        logger.warning(
                            "agent_provenance_pattern_invalid",
                            pattern=entry["pattern"],
                            error=str(exc),
                        )
                        continue
                    sink.append((entry["pattern"], str(entry["agent"])))
    except Exception as exc:  # config parsing must never break indexing
        logger.warning("agent_provenance_config_failed", error=str(exc))
    return AgentProvenanceClassifier(
        extra_service_emails=extra_emails,
        extra_footer_patterns=extra_footers,
        extra_coauthor_patterns=extra_coauthors,
    )
