"""Per-commit agent-provenance classification — deterministic, precision-first.

Labels a commit ``{agent, autonomy_tier, channel, confidence}`` from the
attribution channels available in **local git history** (identity fields,
message footers, ``Co-authored-by:`` trailers — no network, no API calls, no
LLM), in strip-resistance order:

  Tier 1 (near-autonomous — an agent service account authored the commit):
     * commit AUTHOR is a known agent bot account / service e-mail
       (``copilot-swe-agent[bot]``, ``devin-ai-integration[bot]``,
       ``cursoragent@cursor.com``, ...)
  Tier 2 (human-driven agent — the agent wrote the change):
     * commit-message footer (exact service phrases: "Generated with Claude
       Code", opencode, Codex) or the aider author-name suffix ``... (aider)``
     * a service identity as COMMITTER over a human author (the agent
       pushed/amended a human-driven change — deliberately NOT tier 1)
  Tier 3 (assisted — an agent contributed, a human authored):
     * ``Co-authored-by:`` trailer naming a known agent service identity

Precedence is tier order (1 > 2 > 3); first match wins. A commit with no
match is human (``None``). Every pattern is anchored to a *service identity*
(bot login, service e-mail, exact footer phrase) — never a bare name. A loose
name pattern is how a human contributor named "Devin" gets misclassified as
the Devin agent; a false "agent-authored" label on a human commit is worse
than a miss.

PR-level channels (bot PR author, agent branch prefixes, PR-body footers)
require the forge API and are intentionally out of scope here: squash merges
that strip commit trailers are therefore a known recall loss, not a precision
loss. ``confidence`` is carried per channel so future, weaker channels can be
filtered by consumers; every local channel is ``"high"``.

The default registry below is data, not code: repos can extend it from
``.repowise/config.yaml`` (see :func:`classifier_from_repo_config`) without
touching this module, e.g.::

    agent_provenance:
      service_emails:
        mybot@example.com: {agent: mybot, tier: 1}
      footer_patterns:
        - {pattern: "Generated by MyBot", agent: mybot}
      coauthor_patterns:
        - {pattern: "^co-authored-by: mybot <[^>]*@example\\.com>", agent: mybot}

Classification is pure in-memory regex over already-parsed commit records and
rides the existing commit-index walk — it adds no git subprocess and no I/O.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

import structlog

logger = structlog.get_logger(__name__)

__all__ = [
    "AgentProvenance",
    "AgentProvenanceClassifier",
    "classifier_from_repo_config",
]


# ------------------------------------------------------------------ registry --

# Bot login (lowercase, without the ``[bot]`` suffix) → agent name, for
# ``<login>[bot]@users.noreply.github.com`` author/committer e-mails (GitHub's
# canonical bot identity, also re-injected on squash merges).
_BOT_LOGINS: dict[str, str] = {
    "copilot-swe-agent": "copilot",
    "copilot": "copilot",
    "devin-ai-integration": "devin",
    "cursor": "cursor",
    "cursoragent": "cursor",
    "google-labs-jules": "jules",
    "codegen-sh": "codegen",
    "openhands-ai": "openhands",
    "sweep-ai": "sweep",
    "claude": "claude",
}

# Exact service e-mails → (agent, tier) for commit identity fields.
_SERVICE_EMAILS: dict[str, tuple[str, int]] = {
    "cursoragent@cursor.com": ("cursor", 1),
    "devin-ai-integration[bot]@users.noreply.github.com": ("devin", 1),
}

# Commit-message footers → agent (exact service phrases only).
_FOOTER_PATTERNS: list[tuple[str, str]] = [
    (r"generated with \[?claude code\]?", "claude"),
    (r"generated with \[?opencode\]?", "opencode"),
    (r"generated with \[?(?:openai )?codex\]?", "codex"),
    (r"^\s*aider wrote this", "aider"),
]

# ``Co-authored-by:`` trailers → agent. Anchored to the trailer position AND
# the agent's service identity — a name alone is not enough (see module doc).
_COAUTHOR_PATTERNS: list[tuple[str, str]] = [
    (
        r"^co-authored-by:\s*claude(?:\s+(?:opus|sonnet|haiku)[^<]*)?\s*<[^>]*@anthropic\.com>",
        "claude",
    ),
    (r"^co-authored-by:\s*copilot\s*<\d+\+copilot@users\.noreply\.github\.com>", "copilot"),
    (
        r"^co-authored-by:\s*cursor(?:\s*agent)?\s*<(?:cursoragent@cursor\.com|[^>]*cursor[^>]*)>",
        "cursor",
    ),
    (r"^co-authored-by:\s*opencode\s*<", "opencode"),
    (r"^co-authored-by:\s*devin[^<]*<[^>]*devin-ai-integration[^>]*>", "devin"),
    (r"^co-authored-by:\s*aider[^<]*<[^>]*aider[^>]*>", "aider"),
]

_AIDER_NAME_RE = re.compile(r"\(aider\)\s*$")


@dataclass(frozen=True)
class AgentProvenance:
    """One commit's agent attribution. ``agent is None`` means human."""

    agent: str | None = None
    autonomy_tier: int | None = None  # 1 near-autonomous · 2 human-driven · 3 assisted
    channel: str | None = None
    confidence: str | None = None  # "high" | "medium" (local channels: always high)


_HUMAN = AgentProvenance()


class AgentProvenanceClassifier:
    """Compiled pattern registry + the classification rule.

    Construct once per index run (compilation is the only non-trivial cost);
    :meth:`classify` is then a handful of anchored regex searches per commit.
    Extra patterns merge on top of the built-in registry; they never replace
    it (precision of the defaults is validated, user patterns are additive).
    """

    def __init__(
        self,
        *,
        extra_service_emails: dict[str, tuple[str, int]] | None = None,
        extra_footer_patterns: list[tuple[str, str]] | None = None,
        extra_coauthor_patterns: list[tuple[str, str]] | None = None,
    ) -> None:
        self._service_emails = {**_SERVICE_EMAILS, **(extra_service_emails or {})}
        # ``[bot]`` is optional: GitHub squash-merges authored by the Copilot
        # coding agent use ``<id>+Copilot@users.noreply.github.com`` (no
        # suffix). Safe because each login is a unique, vendor-owned GitHub
        # account — no human can register them.
        self._bot_email_re = re.compile(
            r"^(?:\d+\+)?("
            + "|".join(re.escape(b) for b in _BOT_LOGINS)
            + r")(?:\[bot\])?@users\.noreply\.github\.com$",
            re.IGNORECASE,
        )
        self._footers = [
            (re.compile(p, re.IGNORECASE | re.MULTILINE), agent)
            for p, agent in [*_FOOTER_PATTERNS, *(extra_footer_patterns or [])]
        ]
        self._coauthors = [
            (re.compile(p, re.IGNORECASE | re.MULTILINE), agent)
            for p, agent in [*_COAUTHOR_PATTERNS, *(extra_coauthor_patterns or [])]
        ]

    def _identity_match(self, email: str) -> tuple[str, int] | None:
        e = (email or "").strip().lower()
        if not e:
            return None
        hit = self._service_emails.get(e)
        if hit:
            return hit
        m = self._bot_email_re.match(e)
        if m:
            return (_BOT_LOGINS[m.group(1).lower()], 1)
        return None

    def classify(
        self,
        author_name: str,
        author_email: str,
        committer_name: str,
        committer_email: str,
        message: str,
    ) -> AgentProvenance:
        """Classify one commit from local metadata. *message* is the full
        commit message (subject + body) — trailers and footers live in the
        body, so passing the subject alone silently disables two channels."""
        # T1 — agent service identity AUTHORED the commit.
        hit = self._identity_match(author_email)
        if hit:
            return AgentProvenance(hit[0], hit[1], "service_email", "high")
        # T2 — message footer / aider author-name suffix.
        for pat, agent in self._footers:
            if pat.search(message):
                return AgentProvenance(agent, 2, "message_footer", "high")
        if _AIDER_NAME_RE.search(author_name or ""):
            return AgentProvenance("aider", 2, "author_name_aider", "high")
        # T2 — service identity as COMMITTER over a human author: the agent
        # pushed/amended a human-driven change. Deliberately tier 2, not 1.
        hit = self._identity_match(committer_email)
        if hit:
            return AgentProvenance(hit[0], max(hit[1], 2), "service_committer", "high")
        # T3 — co-author trailer naming an agent service identity.
        for pat, agent in self._coauthors:
            if pat.search(message):
                return AgentProvenance(agent, 3, "coauthor_trailer", "high")
        return _HUMAN


def classifier_from_repo_config(repo_path: object) -> AgentProvenanceClassifier:
    """Build a classifier with any repo-local pattern extensions.

    Reads the optional ``agent_provenance`` block of ``.repowise/config.yaml``
    (see module docstring for the shape). Malformed entries are skipped with a
    warning — a broken user pattern must never take down the git index.
    """
    extra_emails: dict[str, tuple[str, int]] = {}
    extra_footers: list[tuple[str, str]] = []
    extra_coauthors: list[tuple[str, str]] = []
    try:
        from ...repo_config import load_repo_config

        block = load_repo_config(repo_path).get("agent_provenance") or {}  # type: ignore[arg-type]
        if isinstance(block, dict):
            for email, spec in (block.get("service_emails") or {}).items():
                if isinstance(spec, dict) and spec.get("agent"):
                    tier = max(1, min(3, int(spec.get("tier", 1))))
                    extra_emails[str(email).lower()] = (str(spec["agent"]), tier)
            for key, sink in (
                ("footer_patterns", extra_footers),
                ("coauthor_patterns", extra_coauthors),
            ):
                for entry in block.get(key) or []:
                    if not (
                        isinstance(entry, dict) and entry.get("pattern") and entry.get("agent")
                    ):
                        continue
                    try:
                        re.compile(entry["pattern"])
                    except re.error as exc:
                        logger.warning(
                            "agent_provenance_pattern_invalid",
                            pattern=entry["pattern"],
                            error=str(exc),
                        )
                        continue
                    sink.append((entry["pattern"], str(entry["agent"])))
    except Exception as exc:  # config parsing must never break indexing
        logger.warning("agent_provenance_config_failed", error=str(exc))
    return AgentProvenanceClassifier(
        extra_service_emails=extra_emails,
        extra_footer_patterns=extra_footers,
        extra_coauthor_patterns=extra_coauthors,
    )
