"""Pydantic request/response models for the repowise REST API.

This package was split out of the former single ``schemas.py`` module. Every
public model is re-exported here so existing
``from repowise.server.schemas import X`` imports keep working unchanged.
"""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ._datetime import UTCDateTime
    from .architecture import (
        ArchEdgeResponse,
        ArchitectureViewResponse,
        ArchLayerResponse,
        ArchNodeResponse,
        ArchSubGroupResponse,
        ArchTourStepResponse,
    )
    from .blast_radius import (
        BlastRadiusRequest,
        BlastRadiusResponse,
        CochangeWarning,
        DirectRiskEntry,
        ReviewerEntry,
        TransitiveEntry,
    )
    from .c4 import (
        C4ComponentResponse,
        C4ContainerResponse,
        C4ExternalSystemResponse,
        C4L1Response,
        C4L2Response,
        C4L3Response,
        C4PersonResponse,
        C4RelationResponse,
        C4SystemResponse,
    )
    from .chat import (
        ArtifactUpdateRequest,
        ChatArtifactEnvelope,
        ChatMessageResponse,
        ChatRequest,
        ChatSuggestion,
        ChatSuggestionsResponse,
        ConversationDetailResponse,
        ConversationForkRequest,
        ConversationResponse,
        ConversationUpdateRequest,
    )
    from .claude_md import ClaudeMdGenerateResponse, ClaudeMdResponse
    from .code_health import (
        ChurnComplexityPoint,
        ChurnComplexityResponse,
        FileHealthTrendResponse,
        FileTrendPointResponse,
        HealthBadgeResponse,
        HealthFileDelta,
        HealthFindingResponse,
        HealthFindingWithSymbolResponse,
        HealthTrendAlert,
        HealthTrendKpiRow,
        HealthTrendResponse,
        HealthTrendSummary,
        HealthWorkItem,
        HealthWorkQueueResponse,
    )
    from .code_quality import (
        DeadCodeAnalyzeResponse,
        DeadCodeFindingResponse,
        DeadCodePatchRequest,
        DeadCodeSummaryResponse,
        RepoStatsResponse,
        SecurityFindingResponse,
    )
    from .coupling import (
        CouplingEdgeResponse,
        CouplingGraphResponse,
        CouplingNodeResponse,
    )
    from .decisions import (
        DecisionCodeEdge,
        DecisionCountsResponse,
        DecisionCreate,
        DecisionDiscoveryBudget,
        DecisionDiscoveryPatch,
        DecisionEvidenceListResponse,
        DecisionEvidenceResponse,
        DecisionGraphEdge,
        DecisionGraphNode,
        DecisionGraphResponse,
        DecisionHealthResponse,
        DecisionLaneCountsResponse,
        DecisionLineageEntry,
        DecisionLineageResponse,
        DecisionRecordResponse,
        DecisionSettings,
        DecisionSettingsUpdate,
        DecisionSourcePatch,
        DecisionSourceState,
        DecisionStatusUpdate,
    )
    from .doc_drift import (
        DocDriftDocumentDriftResponse,
        DocDriftFindingResponse,
        DocDriftReferenceResponse,
        DocDriftReferencesResponse,
        DocDriftResponse,
        DocDriftSummaryResponse,
    )
    from .episodes import (
        EpisodeCountsResponse,
        EpisodeDetail,
        EpisodeListResponse,
        EpisodeSummary,
    )
    from .external_systems import (
        ExternalSystemEntry,
        ExternalSystemsResponse,
    )
    from .git import (
        AgentTrendBucket,
        AgentTrendResponse,
        ChangeFeaturesResponse,
        CoChangeResponse,
        CommitDetailResponse,
        CommitEvolutionBucket,
        CommitEvolutionResponse,
        CommitFileResponse,
        CommitHealthFindingResponse,
        CommitHealthResponse,
        CommitResponse,
        CommitStatsResponse,
        FixHistoryFileResponse,
        FixHistoryResponse,
        GitMetadataResponse,
        GitSummaryResponse,
        HotspotResponse,
        OwnershipEntry,
        RiskDriverResponse,
        RiskHistogramBucket,
        RiskRangeResponse,
    )
    from .graph import (
        ArchitectureEdgeResponse,
        ArchitectureGraphResponse,
        ArchitectureNodeResponse,
        CommunitySliceNodeResponse,
        CommunitySliceResponse,
        DeadCodeGraphNodeResponse,
        DeadCodeGraphResponse,
        DependencyPathResponse,
        EgoGraphResponse,
        GraphEdgeResponse,
        GraphExportResponse,
        GraphNodeResponse,
        HotFilesGraphResponse,
        HotFilesNodeResponse,
        ModuleEdgeResponse,
        ModuleGraphResponse,
        ModuleNodeResponse,
        NodeSearchResult,
        PopulationBreakdown,
        UnclusteredFiles,
    )
    from .health import (
        CoordinatorHealthResponse,
        HealthResponse,
    )
    from .intelligence import (
        CallerCalleeEntry,
        CallersCalleesResponse,
        CommunityDetailResponse,
        CommunityMember,
        CommunitySummaryItem,
        ExecutionFlowEntry,
        ExecutionFlowsResponse,
        GraphMetricsResponse,
        NeighboringCommunity,
        SymbolNodeSummary,
    )
    from .mcp import (
        McpToolInfo,
        McpToolSurfaceResponse,
        UpdateMcpToolsRequest,
    )
    from .meta import (
        ChangelogEntryModel,
        ChangelogResponse,
        ChangelogSectionModel,
        VersionResponse,
    )
    from .ownership import (
        GoverningDecisionRef,
        KnowledgeMapOwner,
        KnowledgeMapResponse,
        KnowledgeMapSilo,
        KnowledgeMapTarget,
        ModuleHealthDetail,
        ModuleHealthOwner,
        ModuleHealthSummary,
        OwnerAgentCollab,
        OwnerCoAuthor,
        OwnerFileEntry,
        OwnerListEntry,
        OwnerModuleRollup,
        OwnerProfileResponse,
        ReviewerSuggestion,
        ReviewerSuggestionsResponse,
    )
    from .pages import (
        JobResponse,
        PageResponse,
        PageSummaryResponse,
        PageVersionResponse,
    )
    from .pagination import Paginated
    from .refactoring import (
        RefactoringOpportunitiesResponse,
        RefactoringOpportunityDetailResponse,
        RefactoringOpportunityStatusResponse,
        RefactoringPlanStatusResponse,
        RefactoringRollupResponse,
    )
    from .repository import (
        JobAcceptedResponse,
        RepoCreate,
        RepoDeletedResponse,
        RepoResponse,
        ReposSummaryResponse,
        RepoSummaryRow,
        RepoUpdate,
    )
    from .search import (
        SearchRequest,
        SearchResultResponse,
    )
    from .symbols import (
        SymbolImportanceComponents,
        SymbolResponse,
    )
    from .ui_helpers import (
        ActiveProviderSelection,
        CostGroupResponse,
        CostSummaryResponse,
        OkResponse,
        ProviderEntry,
        ProviderStatusResponse,
        ProviderValidationResponse,
        SavingsAgentRow,
        SavingsBreakdownRow,
        SavingsOpportunityRow,
        SavingsResponse,
        SetActiveProviderRequest,
        SetApiKeyRequest,
        WebhookResponse,
    )
    from .workspace import (
        WorkspaceArchitectureResponse,
        WorkspaceBlastRadiusResponse,
        WorkspaceBreakingChange,
        WorkspaceBreakingChangesResponse,
        WorkspaceCoChangeEntry,
        WorkspaceCoChangesResponse,
        WorkspaceCoChangeStructure,
        WorkspaceConformanceResponse,
        WorkspaceConformanceViolation,
        WorkspaceContractDetail,
        WorkspaceContractEntry,
        WorkspaceContractLinkEntry,
        WorkspaceContractsResponse,
        WorkspaceContractSummary,
        WorkspaceCrossRepoSummary,
        WorkspaceDependencyCycle,
        WorkspaceExtractionDiagnostics,
        WorkspaceGraphEdge,
        WorkspaceGraphNode,
        WorkspaceGraphResponse,
        WorkspaceImpactedConsumer,
        WorkspaceImpactedNode,
        WorkspaceOrphanProvider,
        WorkspaceRepoDiagnostics,
        WorkspaceRepoEntry,
        WorkspaceRepoRemovedResponse,
        WorkspaceResponse,
        WorkspaceSyncResponse,
        WorkspaceSyncResult,
        WorkspaceSystemEdge,
        WorkspaceSystemGraphResponse,
        WorkspaceSystemNode,
        WorkspaceTestImpactFile,
        WorkspaceTestImpactResponse,
        WorkspaceTestRecommendation,
        WorkspaceUnmatchedConsumer,
        WorkspaceUnresolvedLink,
    )
    from .zoom import (
        ZoomMapResponse,
        ZoomMetricsResponse,
        ZoomNodeResponse,
        ZoomRelationResponse,
    )

# Loaded on first access (PEP 562), so importing one model does not pay for
# every submodule, one of which pulls in the whole dead-code analyzer.
_EXPORTS: dict[str, tuple[str, ...]] = {
    "_datetime": ("UTCDateTime",),
    "architecture": (
        "ArchEdgeResponse",
        "ArchitectureViewResponse",
        "ArchLayerResponse",
        "ArchNodeResponse",
        "ArchSubGroupResponse",
        "ArchTourStepResponse",
    ),
    "blast_radius": (
        "BlastRadiusRequest",
        "BlastRadiusResponse",
        "CochangeWarning",
        "DirectRiskEntry",
        "ReviewerEntry",
        "TransitiveEntry",
    ),
    "c4": (
        "C4ComponentResponse",
        "C4ContainerResponse",
        "C4ExternalSystemResponse",
        "C4L1Response",
        "C4L2Response",
        "C4L3Response",
        "C4PersonResponse",
        "C4RelationResponse",
        "C4SystemResponse",
    ),
    "chat": (
        "ArtifactUpdateRequest",
        "ChatArtifactEnvelope",
        "ChatMessageResponse",
        "ChatRequest",
        "ChatSuggestion",
        "ChatSuggestionsResponse",
        "ConversationDetailResponse",
        "ConversationForkRequest",
        "ConversationResponse",
        "ConversationUpdateRequest",
    ),
    "claude_md": ("ClaudeMdGenerateResponse", "ClaudeMdResponse"),
    "code_health": (
        "ChurnComplexityPoint",
        "ChurnComplexityResponse",
        "FileHealthTrendResponse",
        "FileTrendPointResponse",
        "HealthBadgeResponse",
        "HealthFileDelta",
        "HealthFindingResponse",
        "HealthFindingWithSymbolResponse",
        "HealthTrendAlert",
        "HealthTrendKpiRow",
        "HealthTrendResponse",
        "HealthTrendSummary",
        "HealthWorkItem",
        "HealthWorkQueueResponse",
    ),
    "code_quality": (
        "DeadCodeAnalyzeResponse",
        "DeadCodeFindingResponse",
        "DeadCodePatchRequest",
        "DeadCodeSummaryResponse",
        "RepoStatsResponse",
        "SecurityFindingResponse",
    ),
    "coupling": ("CouplingEdgeResponse", "CouplingGraphResponse", "CouplingNodeResponse"),
    "decisions": (
        "DecisionCodeEdge",
        "DecisionCountsResponse",
        "DecisionCreate",
        "DecisionDiscoveryBudget",
        "DecisionDiscoveryPatch",
        "DecisionEvidenceListResponse",
        "DecisionEvidenceResponse",
        "DecisionGraphEdge",
        "DecisionGraphNode",
        "DecisionGraphResponse",
        "DecisionHealthResponse",
        "DecisionLaneCountsResponse",
        "DecisionLineageEntry",
        "DecisionLineageResponse",
        "DecisionRecordResponse",
        "DecisionSettings",
        "DecisionSettingsUpdate",
        "DecisionSourcePatch",
        "DecisionSourceState",
        "DecisionStatusUpdate",
    ),
    "doc_drift": (
        "DocDriftDocumentDriftResponse",
        "DocDriftFindingResponse",
        "DocDriftReferenceResponse",
        "DocDriftReferencesResponse",
        "DocDriftResponse",
        "DocDriftSummaryResponse",
    ),
    "episodes": ("EpisodeCountsResponse", "EpisodeDetail", "EpisodeListResponse", "EpisodeSummary"),
    "external_systems": ("ExternalSystemEntry", "ExternalSystemsResponse"),
    "git": (
        "AgentTrendBucket",
        "AgentTrendResponse",
        "ChangeFeaturesResponse",
        "CoChangeResponse",
        "CommitDetailResponse",
        "CommitEvolutionBucket",
        "CommitEvolutionResponse",
        "CommitFileResponse",
        "CommitHealthFindingResponse",
        "CommitHealthResponse",
        "CommitResponse",
        "CommitStatsResponse",
        "FixHistoryFileResponse",
        "FixHistoryResponse",
        "GitMetadataResponse",
        "GitSummaryResponse",
        "HotspotResponse",
        "OwnershipEntry",
        "RiskDriverResponse",
        "RiskHistogramBucket",
        "RiskRangeResponse",
    ),
    "graph": (
        "ArchitectureEdgeResponse",
        "ArchitectureGraphResponse",
        "ArchitectureNodeResponse",
        "CommunitySliceNodeResponse",
        "CommunitySliceResponse",
        "DeadCodeGraphNodeResponse",
        "DeadCodeGraphResponse",
        "DependencyPathResponse",
        "EgoGraphResponse",
        "GraphEdgeResponse",
        "GraphExportResponse",
        "GraphNodeResponse",
        "HotFilesGraphResponse",
        "HotFilesNodeResponse",
        "ModuleEdgeResponse",
        "ModuleGraphResponse",
        "ModuleNodeResponse",
        "NodeSearchResult",
        "PopulationBreakdown",
        "UnclusteredFiles",
    ),
    "health": ("CoordinatorHealthResponse", "HealthResponse"),
    "intelligence": (
        "CallerCalleeEntry",
        "CallersCalleesResponse",
        "CommunityDetailResponse",
        "CommunityMember",
        "CommunitySummaryItem",
        "ExecutionFlowEntry",
        "ExecutionFlowsResponse",
        "GraphMetricsResponse",
        "NeighboringCommunity",
        "SymbolNodeSummary",
    ),
    "mcp": ("McpToolInfo", "McpToolSurfaceResponse", "UpdateMcpToolsRequest"),
    "meta": (
        "ChangelogEntryModel",
        "ChangelogResponse",
        "ChangelogSectionModel",
        "VersionResponse",
    ),
    "ownership": (
        "GoverningDecisionRef",
        "KnowledgeMapOwner",
        "KnowledgeMapResponse",
        "KnowledgeMapSilo",
        "KnowledgeMapTarget",
        "ModuleHealthDetail",
        "ModuleHealthOwner",
        "ModuleHealthSummary",
        "OwnerAgentCollab",
        "OwnerCoAuthor",
        "OwnerFileEntry",
        "OwnerListEntry",
        "OwnerModuleRollup",
        "OwnerProfileResponse",
        "ReviewerSuggestion",
        "ReviewerSuggestionsResponse",
    ),
    "pages": ("JobResponse", "PageResponse", "PageSummaryResponse", "PageVersionResponse"),
    "pagination": ("Paginated",),
    "refactoring": (
        "RefactoringOpportunitiesResponse",
        "RefactoringOpportunityDetailResponse",
        "RefactoringOpportunityStatusResponse",
        "RefactoringPlanStatusResponse",
        "RefactoringRollupResponse",
    ),
    "repository": (
        "JobAcceptedResponse",
        "RepoCreate",
        "RepoDeletedResponse",
        "RepoResponse",
        "ReposSummaryResponse",
        "RepoSummaryRow",
        "RepoUpdate",
    ),
    "search": ("SearchRequest", "SearchResultResponse"),
    "symbols": ("SymbolImportanceComponents", "SymbolResponse"),
    "ui_helpers": (
        "ActiveProviderSelection",
        "CostGroupResponse",
        "CostSummaryResponse",
        "OkResponse",
        "ProviderEntry",
        "ProviderStatusResponse",
        "ProviderValidationResponse",
        "SavingsAgentRow",
        "SavingsBreakdownRow",
        "SavingsOpportunityRow",
        "SavingsResponse",
        "SetActiveProviderRequest",
        "SetApiKeyRequest",
        "WebhookResponse",
    ),
    "workspace": (
        "WorkspaceArchitectureResponse",
        "WorkspaceBlastRadiusResponse",
        "WorkspaceBreakingChange",
        "WorkspaceBreakingChangesResponse",
        "WorkspaceCoChangeEntry",
        "WorkspaceCoChangesResponse",
        "WorkspaceCoChangeStructure",
        "WorkspaceConformanceResponse",
        "WorkspaceConformanceViolation",
        "WorkspaceContractDetail",
        "WorkspaceContractEntry",
        "WorkspaceContractLinkEntry",
        "WorkspaceContractsResponse",
        "WorkspaceContractSummary",
        "WorkspaceCrossRepoSummary",
        "WorkspaceDependencyCycle",
        "WorkspaceExtractionDiagnostics",
        "WorkspaceGraphEdge",
        "WorkspaceGraphNode",
        "WorkspaceGraphResponse",
        "WorkspaceImpactedConsumer",
        "WorkspaceImpactedNode",
        "WorkspaceOrphanProvider",
        "WorkspaceRepoDiagnostics",
        "WorkspaceRepoEntry",
        "WorkspaceRepoRemovedResponse",
        "WorkspaceResponse",
        "WorkspaceSyncResponse",
        "WorkspaceSyncResult",
        "WorkspaceSystemEdge",
        "WorkspaceSystemGraphResponse",
        "WorkspaceSystemNode",
        "WorkspaceTestImpactFile",
        "WorkspaceTestImpactResponse",
        "WorkspaceTestRecommendation",
        "WorkspaceUnmatchedConsumer",
        "WorkspaceUnresolvedLink",
    ),
    "zoom": ("ZoomMapResponse", "ZoomMetricsResponse", "ZoomNodeResponse", "ZoomRelationResponse"),
}

_SUBMODULE_OF = {name: module for module, names in _EXPORTS.items() for name in names}

# Runtime only: a visible module __getattr__ would make type checkers accept
# any misspelled name as Any.
if not TYPE_CHECKING:

    def __getattr__(name: str) -> Any:
        module = _SUBMODULE_OF.get(name)
        if module is None:
            raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
        value = getattr(importlib.import_module(f".{module}", __name__), name)
        globals()[name] = value
        return value

    def __dir__() -> list[str]:
        return sorted({*globals(), *__all__})


__all__ = [
    "ActiveProviderSelection",
    "AgentTrendBucket",
    "AgentTrendResponse",
    "ArchEdgeResponse",
    "ArchLayerResponse",
    "ArchNodeResponse",
    "ArchSubGroupResponse",
    "ArchTourStepResponse",
    "ArchitectureEdgeResponse",
    "ArchitectureGraphResponse",
    "ArchitectureNodeResponse",
    "ArchitectureViewResponse",
    "ArtifactUpdateRequest",
    "BlastRadiusRequest",
    "BlastRadiusResponse",
    "C4ComponentResponse",
    "C4ContainerResponse",
    "C4ExternalSystemResponse",
    "C4L1Response",
    "C4L2Response",
    "C4L3Response",
    "C4PersonResponse",
    "C4RelationResponse",
    "C4SystemResponse",
    "CallerCalleeEntry",
    "CallersCalleesResponse",
    "ChangeFeaturesResponse",
    "ChangelogEntryModel",
    "ChangelogResponse",
    "ChangelogSectionModel",
    "ChatArtifactEnvelope",
    "ChatMessageResponse",
    "ChatRequest",
    "ChatSuggestion",
    "ChatSuggestionsResponse",
    "ChurnComplexityPoint",
    "ChurnComplexityResponse",
    "ClaudeMdGenerateResponse",
    "ClaudeMdResponse",
    "CoChangeResponse",
    "CochangeWarning",
    "CommitDetailResponse",
    "CommitEvolutionBucket",
    "CommitEvolutionResponse",
    "CommitFileResponse",
    "CommitHealthFindingResponse",
    "CommitHealthResponse",
    "CommitResponse",
    "CommitStatsResponse",
    "CommunityDetailResponse",
    "CommunityMember",
    "CommunitySliceNodeResponse",
    "CommunitySliceResponse",
    "CommunitySummaryItem",
    "ConversationDetailResponse",
    "ConversationForkRequest",
    "ConversationResponse",
    "ConversationUpdateRequest",
    "CoordinatorHealthResponse",
    "CostGroupResponse",
    "CostSummaryResponse",
    "CouplingEdgeResponse",
    "CouplingGraphResponse",
    "CouplingNodeResponse",
    "DeadCodeAnalyzeResponse",
    "DeadCodeFindingResponse",
    "DeadCodeGraphNodeResponse",
    "DeadCodeGraphResponse",
    "DeadCodePatchRequest",
    "DeadCodeSummaryResponse",
    "DecisionCodeEdge",
    "DecisionCountsResponse",
    "DecisionCreate",
    "DecisionDiscoveryBudget",
    "DecisionDiscoveryPatch",
    "DecisionEvidenceListResponse",
    "DecisionEvidenceResponse",
    "DecisionGraphEdge",
    "DecisionGraphNode",
    "DecisionGraphResponse",
    "DecisionHealthResponse",
    "DecisionLaneCountsResponse",
    "DecisionLineageEntry",
    "DecisionLineageResponse",
    "DecisionRecordResponse",
    "DecisionSettings",
    "DecisionSettingsUpdate",
    "DecisionSourcePatch",
    "DecisionSourceState",
    "DecisionStatusUpdate",
    "DependencyPathResponse",
    "DirectRiskEntry",
    "DocDriftDocumentDriftResponse",
    "DocDriftFindingResponse",
    "DocDriftReferenceResponse",
    "DocDriftReferencesResponse",
    "DocDriftResponse",
    "DocDriftSummaryResponse",
    "EgoGraphResponse",
    "EpisodeCountsResponse",
    "EpisodeDetail",
    "EpisodeListResponse",
    "EpisodeSummary",
    "ExecutionFlowEntry",
    "ExecutionFlowsResponse",
    "ExternalSystemEntry",
    "ExternalSystemsResponse",
    "FileHealthTrendResponse",
    "FileTrendPointResponse",
    "FixHistoryFileResponse",
    "FixHistoryResponse",
    "GitMetadataResponse",
    "GitSummaryResponse",
    "GoverningDecisionRef",
    "GraphEdgeResponse",
    "GraphExportResponse",
    "GraphMetricsResponse",
    "GraphNodeResponse",
    "HealthBadgeResponse",
    "HealthFileDelta",
    "HealthFindingResponse",
    "HealthFindingWithSymbolResponse",
    "HealthResponse",
    "HealthTrendAlert",
    "HealthTrendKpiRow",
    "HealthTrendResponse",
    "HealthTrendSummary",
    "HealthWorkItem",
    "HealthWorkQueueResponse",
    "HotFilesGraphResponse",
    "HotFilesNodeResponse",
    "HotspotResponse",
    "JobAcceptedResponse",
    "JobResponse",
    "KnowledgeMapOwner",
    "KnowledgeMapResponse",
    "KnowledgeMapSilo",
    "KnowledgeMapTarget",
    "McpToolInfo",
    "McpToolSurfaceResponse",
    "ModuleEdgeResponse",
    "ModuleGraphResponse",
    "ModuleHealthDetail",
    "ModuleHealthOwner",
    "ModuleHealthSummary",
    "ModuleNodeResponse",
    "NeighboringCommunity",
    "NodeSearchResult",
    "OkResponse",
    "OwnerAgentCollab",
    "OwnerCoAuthor",
    "OwnerFileEntry",
    "OwnerListEntry",
    "OwnerModuleRollup",
    "OwnerProfileResponse",
    "OwnershipEntry",
    "PageResponse",
    "PageSummaryResponse",
    "PageVersionResponse",
    "Paginated",
    "PopulationBreakdown",
    "ProviderEntry",
    "ProviderStatusResponse",
    "ProviderValidationResponse",
    "RefactoringOpportunitiesResponse",
    "RefactoringOpportunityDetailResponse",
    "RefactoringOpportunityStatusResponse",
    "RefactoringPlanStatusResponse",
    "RefactoringRollupResponse",
    "RepoCreate",
    "RepoDeletedResponse",
    "RepoResponse",
    "RepoStatsResponse",
    "RepoSummaryRow",
    "RepoUpdate",
    "ReposSummaryResponse",
    "ReviewerEntry",
    "ReviewerSuggestion",
    "ReviewerSuggestionsResponse",
    "RiskDriverResponse",
    "RiskHistogramBucket",
    "RiskRangeResponse",
    "SavingsAgentRow",
    "SavingsBreakdownRow",
    "SavingsOpportunityRow",
    "SavingsResponse",
    "SearchRequest",
    "SearchResultResponse",
    "SecurityFindingResponse",
    "SetActiveProviderRequest",
    "SetApiKeyRequest",
    "SymbolImportanceComponents",
    "SymbolNodeSummary",
    "SymbolResponse",
    "TransitiveEntry",
    "UTCDateTime",
    "UnclusteredFiles",
    "UpdateMcpToolsRequest",
    "VersionResponse",
    "WebhookResponse",
    "WorkspaceArchitectureResponse",
    "WorkspaceBlastRadiusResponse",
    "WorkspaceBreakingChange",
    "WorkspaceBreakingChangesResponse",
    "WorkspaceCoChangeEntry",
    "WorkspaceCoChangeStructure",
    "WorkspaceCoChangesResponse",
    "WorkspaceConformanceResponse",
    "WorkspaceConformanceViolation",
    "WorkspaceContractDetail",
    "WorkspaceContractEntry",
    "WorkspaceContractLinkEntry",
    "WorkspaceContractSummary",
    "WorkspaceContractsResponse",
    "WorkspaceCrossRepoSummary",
    "WorkspaceDependencyCycle",
    "WorkspaceExtractionDiagnostics",
    "WorkspaceGraphEdge",
    "WorkspaceGraphNode",
    "WorkspaceGraphResponse",
    "WorkspaceImpactedConsumer",
    "WorkspaceImpactedNode",
    "WorkspaceOrphanProvider",
    "WorkspaceRepoDiagnostics",
    "WorkspaceRepoEntry",
    "WorkspaceRepoRemovedResponse",
    "WorkspaceResponse",
    "WorkspaceSyncResponse",
    "WorkspaceSyncResult",
    "WorkspaceSystemEdge",
    "WorkspaceSystemGraphResponse",
    "WorkspaceSystemNode",
    "WorkspaceTestImpactFile",
    "WorkspaceTestImpactResponse",
    "WorkspaceTestRecommendation",
    "WorkspaceUnmatchedConsumer",
    "WorkspaceUnresolvedLink",
    "ZoomMapResponse",
    "ZoomMetricsResponse",
    "ZoomNodeResponse",
    "ZoomRelationResponse",
]
