"""Emit a Structurizr DSL model from an indexed repository.

One entry point, :func:`to_dsl`, which takes the already-built
:class:`~..models.C4Model` dataclass and returns text. Nothing below this
module touches a database — that is what keeps the emitter unit-testable
without infrastructure, and what keeps emission itself close to free.

Two shapes come out of here:

* **A model fragment** (the default). Just the contents of ``model { … }``,
  meant to be ``!include``d from the user's own ``workspace.dsl`` where their
  views, styles and docs live. We own the model, they own the presentation,
  and regenerating can never clobber hand-written work.
* **A standalone workspace** (``standalone=True``), for someone who has
  nothing yet: the same model wrapped in a ``workspace`` block with default
  views so the file opens and renders on its own.

Identifiers are flat and globally unique, so the fragment resolves inside any
host workspace without that workspace having to opt into a particular
identifier mode.
"""

from __future__ import annotations

from ..models import C4Model
from .elements import write_container, write_external, write_person
from .identifiers import identifiers_for
from .relationships import write_relationships
from .views import write_views
from .writer import Writer, quote

__all__ = ["to_dsl"]

#: Name of the file we tell users to include. Referenced in the header
#: comment so the file explains itself when it arrives without the terminal
#: output that produced it.
DEFAULT_FILENAME = "repowise-model.dsl"


def _reference_map(model: C4Model, *, include_components: bool) -> dict[str, str]:
    """Map every node id to the identifier used to declare and refer to it.

    Identifiers are **flat and globally unique**, which is the DSL's default
    mode. The alternative, ``!identifiers hierarchical``, gives shorter
    component names but makes every reference a dotted path that only resolves
    when the *host* workspace has turned that mode on — and the whole point of
    shipping a fragment is that it drops into a workspace the user already
    owns without them changing anything in it. Uniqueness is handled by
    :func:`~.identifiers.identifiers_for` instead, so nothing is lost but
    brevity.
    """
    # The system's own id is ``sys:<repository uuid>``, which is stable for one
    # machine and different on every other one — two people exporting the same
    # repo would get files that differ in every reference. Key it on the repo
    # name instead, which is the same everywhere. It still goes through the
    # same allocator, so a name that clashes with something else is handled.
    system_key = f"sys:{model.system.name}"
    raw_ids = (
        [system_key]
        + [p.id for p in model.people]
        + [e.id for e in model.external_systems]
        + [c.id for c in model.containers]
    )
    if include_components:
        raw_ids += [
            component.id
            for container in model.containers
            for component in model.components_by_container.get(container.id, [])
        ]
    references = identifiers_for(raw_ids)
    references[model.system.id] = references.pop(system_key)
    return references


def _write_header(writer: Writer, model: C4Model, *, standalone: bool) -> None:
    """The comment block a person reads first, in their editor or a diff.

    Deliberately carries no timestamp: a timestamp makes every regeneration a
    diff, which destroys the "commit it and watch it change meaningfully"
    workflow this file exists for.
    """
    writer.comment(f"Structurizr DSL model for {model.system.name}, generated by Repowise.")
    writer.comment()
    writer.comment("Regenerating overwrites this file — do not hand-edit it.")
    if not standalone:
        writer.comment("It holds the model only; your views, styles and docs stay in")
        writer.comment("your own workspace.dsl, which this is meant to be included from:")
        writer.comment()
        writer.comment(f"    !include {DEFAULT_FILENAME}")
    writer.comment()


def to_dsl(
    model: C4Model,
    *,
    standalone: bool = False,
    include_components: bool = False,
    include_externals: bool = True,
) -> str:
    """Render *model* as Structurizr DSL.

    ``include_components`` is off by default. In a hand-curated Structurizr
    model a component is a grouping somebody chose; ours is a directory, and
    the architects most likely to want this export are exactly the readers who
    would notice the difference.
    """
    writer = Writer()
    _write_header(writer, model, standalone=standalone)

    externals = list(model.external_systems) if include_externals else []
    references = _reference_map(model, include_components=include_components)
    if not include_externals:
        for external in model.external_systems:
            references.pop(external.id, None)

    def write_model_body() -> None:
        for person in sorted(model.people, key=lambda p: p.name):
            write_person(writer, person, references[person.id])
        if model.people:
            writer.blank()

        system_header = f"{references[model.system.id]} = softwareSystem {quote(model.system.name)}"
        if model.system.description:
            system_header += f" {quote(model.system.description)}"
        with writer.block(system_header):
            for index, container in enumerate(sorted(model.containers, key=lambda c: c.path)):
                if index:
                    writer.blank()
                components = (
                    sorted(
                        model.components_by_container.get(container.id, []),
                        key=lambda c: c.path,
                    )
                    if include_components
                    else []
                )
                write_container(
                    writer,
                    container,
                    references[container.id],
                    components,
                    {c.id: references[c.id] for c in components},
                )

        if externals:
            writer.blank()
            for external in sorted(externals, key=lambda e: e.name):
                write_external(writer, external, references[external.id])

        relations = list(model.container_relations)
        if include_components:
            relations = list(model.component_relations)
            # Container-level edges to externals survive the component roll-up
            # only when a component is not the more precise source, so both
            # sets are offered and the dedup below keeps the precise one.
            seen = {(r.source_id, r.target_id) for r in relations}
            relations += [
                r for r in model.container_relations if (r.source_id, r.target_id) not in seen
            ]
        writer.blank()
        writer.comment("Relationships")
        write_relationships(writer, relations, references)

    if not standalone:
        with writer.block("model"):
            write_model_body()
        return writer.render()

    with writer.block(f"workspace {quote(model.system.name)}"):
        with writer.block("model"):
            write_model_body()
        writer.blank()
        write_views(
            writer,
            model,
            references,
            include_components=include_components,
        )
    return writer.render()
