"""CRUD operations for the analysis domain (repowise persistence layer).

Split out of the former monolithic ``crud.py`` and later from the single
``analysis.py`` module into per-entity submodules. ``crud/__init__.py``
re-exports every public name via ``from .analysis import *``, so existing
imports are unaffected.
"""

from __future__ import annotations

from . import coverage, coverage_map, dead_code, health, performance, refactoring  # noqa: F401
from .coverage import (
    get_coverage_summary,
    load_coverage_for_repo,
    save_coverage_files,
)
from .coverage_map import (
    covered_source_files,
    files_covered_by,
    get_test_coverage_summary,
    save_test_coverage,
    tests_covering,
    tests_covering_files,
)
from .dead_code import (
    get_dead_code_findings,
    get_dead_code_summary,
    replace_dead_code_findings,
    save_dead_code_findings,
    update_dead_code_status,
)
from .health import (
    FILE_TREND_SNAPSHOT_WINDOW,
    HEALTH_SNAPSHOT_RETENTION,
    HealthSnapshotHeadline,
    HealthSnapshotScalars,
    backfill_module_attribution,
    get_average_health,
    get_deduction_by_path,
    get_file_language_map,
    get_health_findings,
    get_health_metrics,
    get_health_snapshot_file_counts,
    get_health_snapshot_headline,
    get_health_summary,
    get_perf_coverage,
    list_health_snapshots,
    replace_governance_findings,
    save_health_findings,
    save_health_metrics,
    save_health_snapshot,
    sort_metrics_worst_first,
    update_health_finding_status,
    upsert_health_findings,
    upsert_health_metrics,
)
from .performance import (
    finalize_performance_opportunities,
    get_health_finding_by_public_id,
    get_performance_opportunity,
    get_performance_plan_rows,
    get_performance_summary,
    list_evidence_for_opportunities,
    list_opportunity_evidence,
    list_performance_opportunities,
    opportunity_details,
    performance_facet_counts,
    performance_file_rollups,
)
from .refactoring import (
    count_refactoring_suggestions,
    finalize_refactoring_suggestions,
    get_refactoring_suggestion,
    get_refactoring_suggestions,
    save_refactoring_suggestions,
    update_refactoring_suggestion_status,
    upsert_refactoring_suggestions,
)
from .refactoring_opportunities import (
    finalize_refactoring_opportunities,
    get_refactoring_opportunity,
    get_refactoring_summary,
    list_refactoring_opportunities,
    refactoring_facet_counts,
    update_refactoring_opportunity_status,
)

__all__ = [
    "FILE_TREND_SNAPSHOT_WINDOW",
    "HEALTH_SNAPSHOT_RETENTION",
    "HealthSnapshotHeadline",
    "HealthSnapshotScalars",
    "backfill_module_attribution",
    "count_refactoring_suggestions",
    "covered_source_files",
    "files_covered_by",
    "finalize_performance_opportunities",
    "finalize_refactoring_opportunities",
    "finalize_refactoring_suggestions",
    "get_average_health",
    "get_coverage_summary",
    "get_dead_code_findings",
    "get_dead_code_summary",
    "get_deduction_by_path",
    "get_file_language_map",
    "get_health_finding_by_public_id",
    "get_health_findings",
    "get_health_metrics",
    "get_health_snapshot_file_counts",
    "get_health_snapshot_headline",
    "get_health_summary",
    "get_perf_coverage",
    "get_performance_opportunity",
    "get_performance_plan_rows",
    "get_performance_summary",
    "get_refactoring_opportunity",
    "get_refactoring_suggestion",
    "get_refactoring_suggestions",
    "get_refactoring_summary",
    "get_test_coverage_summary",
    "list_evidence_for_opportunities",
    "list_health_snapshots",
    "list_opportunity_evidence",
    "list_performance_opportunities",
    "list_refactoring_opportunities",
    "load_coverage_for_repo",
    "opportunity_details",
    "performance_facet_counts",
    "performance_file_rollups",
    "refactoring_facet_counts",
    "replace_dead_code_findings",
    "replace_governance_findings",
    "save_coverage_files",
    "save_dead_code_findings",
    "save_health_findings",
    "save_health_metrics",
    "save_health_snapshot",
    "save_refactoring_suggestions",
    "save_test_coverage",
    "sort_metrics_worst_first",
    "tests_covering",
    "tests_covering_files",
    "update_dead_code_status",
    "update_health_finding_status",
    "update_refactoring_opportunity_status",
    "update_refactoring_suggestion_status",
    "upsert_health_findings",
    "upsert_health_metrics",
    "upsert_refactoring_suggestions",
]
