// Bundles src/register.ts into the plugin's hooks module.
//
//   node build.mjs           write plugins/claude-code/hooks/lens/lens.js
//   node build.mjs --check   exit 1 when the committed bundle has drifted
//
// The mod runtime loads only files inside the plugin dir, so the shared
// packages are inlined. Never minified: the engine's static check reads `$`
// calls by name. Output is deterministic (relative paths, no legal comments,
// LF) so a rebuild on any OS matches the committed file.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../..");
const outFile = resolve(repoRoot, "plugins/claude-code/hooks/lens/lens.js");
const check = process.argv.includes("--check");

const result = await build({
  entryPoints: [resolve(here, "src/register.ts")],
  absWorkingDir: here,
  bundle: true,
  format: "esm",
  platform: "neutral",
  mainFields: ["module", "main"],
  keepNames: true,
  minify: false,
  legalComments: "none",
  charset: "utf8",
  write: false,
  logLevel: "warning",
});

const banner = "// Generated by packages/claude-mod (npm run build:mod). Do not edit.\n";
const output = banner + result.outputFiles[0].text.replace(/\r\n/g, "\n");

if (check) {
  let current = "";
  try {
    current = (await readFile(outFile, "utf8")).replace(/\r\n/g, "\n");
  } catch (err) {
    // A missing bundle is drift, reported below; any other read error fails loudly.
    if (err?.code !== "ENOENT") throw new Error(`cannot read ${outFile}`, { cause: err });
  }
  if (current !== output) {
    console.error(`${outFile} is out of date. Run: npm run build:mod -w @repowise-dev/claude-mod`);
    process.exit(1);
  }
  console.log("lens.js is up to date");
} else {
  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, output);
  console.log(`wrote ${outFile} (${Buffer.byteLength(output)} bytes)`);
}
