{{- if and .Values.gitCredentials.github.token (not .Values.gitCredentials.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "repowise.fullname" . }}-git-credentials
  labels:
    {{- include "repowise.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
type: Opaque
stringData:
  git-credentials: "https://{{ .Values.gitCredentials.github.username }}:{{ .Values.gitCredentials.github.token }}@github.com"
{{- end }}
