{{- if .Values.secret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "repowise.fullname" . }}-secret
  labels:
    {{- include "repowise.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secret.anthropicApiKey | quote }}
  {{- end }}
  {{- if .Values.secret.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secret.openaiApiKey | quote }}
  {{- end }}
  {{- if .Values.secret.geminiApiKey }}
  GEMINI_API_KEY: {{ .Values.secret.geminiApiKey | quote }}
  {{- end }}
  {{- if .Values.secret.repowiseApiKey }}
  REPOWISE_API_KEY: {{ .Values.secret.repowiseApiKey | quote }}
  {{- end }}
{{- end }}
