{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "repowise.fullname" . }}
  labels:
    {{- include "repowise.labels" . | nindent 4 }}
type: Opaque
data:
  ANTHROPIC_API_KEY: {{ .Values.apiKeys.anthropic | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.apiKeys.openai | b64enc | quote }}
  GEMINI_API_KEY: {{ .Values.apiKeys.gemini | b64enc | quote }}
{{- end }}
