"""One origin per file: production, test, vendored, docs_example, generated, tooling."""

from __future__ import annotations

import pytest

from repowise.core.code_origin import CODE_ORIGINS, code_origin, is_generated_header

_JQUERY = (
    "/*!\n"
    " * jQuery JavaScript Library v3.6.0\n"
    " * https://jquery.com/\n"
    " * Copyright OpenJS Foundation and other contributors\n"
    " * Released under the MIT license\n"
    " */\n"
    "(function (global, factory) {\n"
)
_TYPEAHEAD = (
    "/*!\n"
    " * typeahead.js 0.10.5\n"
    " * https://github.com/twitter/typeahead.js\n"
    " * Copyright 2013-2014 Twitter, Inc. and other contributors; Licensed MIT\n"
    " */\n"
)
_OWN_HEADER = (
    "// Copyright (c) 2024 Acme Corp. All rights reserved.\n"
    "// Licensed under the MIT License.\n"
    "export function boot() {}\n"
)


@pytest.mark.parametrize(
    ("path", "expected"),
    [
        ("src/flask/app.py", "production"),
        ("app.py", "production"),
        ("src/examples.py", "production"),  # a file named for examples is code
        ("pkg/external_api/client.go", "production"),
        ("pkg/external/client.go", "production"),  # external/ only at the root
        ("tests/test_app.py", "test"),
        ("src/app.test.ts", "test"),
        ("vendor/github.com/x/y.go", "vendored"),
        ("web/node_modules/lodash/index.js", "vendored"),
        ("static/bower_components/jquery/jquery.js", "vendored"),
        ("third_party/zlib/inflate.c", "vendored"),
        ("src/thirdparty/docopt.py", "vendored"),
        ("external/abseil/str.cc", "vendored"),
        ("static/js/app.min.js", "vendored"),
        ("assets/site.min.css", "vendored"),
        ("docs_src/tutorial/first_steps.py", "docs_example"),
        ("docs/conf.py", "docs_example"),
        ("doc/man_docs.go", "production"),  # cobra's doc/ is a shipped package
        ("examples/tutorial/app.py", "docs_example"),
        ("example/main.go", "docs_example"),
        ("samples/hello/Program.cs", "docs_example"),
        ("tutorials/part1/app.js", "docs_example"),
        ("tutorial_01/app.py", "docs_example"),
        ("scripts/release.py", "tooling"),
        (".github/scripts/label.js", "tooling"),
        ("tools/gen.go", "tooling"),
        ("benchmarks/bench_app.py", "tooling"),
        ("app/migrations/0001_initial.py", "tooling"),
        ("db/alembic/versions/abc_add.py", "tooling"),
        ("setup.py", "tooling"),
        ("vite.config.ts", "tooling"),
        ("src/__generated__/schema.ts", "generated"),
        ("api/user_pb2.py", "generated"),
        ("api/user_grpc.pb.go", "generated"),
        ("Forms/Main.Designer.cs", "generated"),
        ("src/client.generated.ts", "generated"),
    ],
)
def test_path_rules(path: str, expected: str) -> None:
    assert code_origin(path) == expected


def test_every_answer_is_one_of_the_six() -> None:
    assert set(CODE_ORIGINS) == {
        "production",
        "test",
        "vendored",
        "docs_example",
        "generated",
        "tooling",
    }


def test_precedence_is_generated_vendored_test_docs_tooling() -> None:
    assert code_origin("vendor/foo_test.go") == "vendored"
    assert code_origin("docs/tests/test_x.py") == "test"
    assert code_origin("examples/scripts/run.py") == "docs_example"
    assert code_origin("vendor/x.go", "// Code generated by protoc. DO NOT EDIT.\n") == "generated"


def test_stored_test_flag_wins_over_the_path() -> None:
    assert code_origin("src/checks.py", is_test=True) == "test"
    assert code_origin("tests/test_app.py", is_test=False) == "production"


def test_generated_banner_in_the_header() -> None:
    assert code_origin("pkg/x.go", b"// Code generated by stringer. DO NOT EDIT.\n") == "generated"
    assert code_origin("pkg/x.py", '"""Auto-generated by the build."""\n') == "generated"


def test_generated_banner_negatives() -> None:
    # A string literal mentioning codegen is not a banner.
    assert code_origin("pkg/x.py", 'MSG = "auto-generated client"\n') == "production"
    # A banner below the second line is not a header.
    assert not is_generated_header("a = 1\nb = 2\n# DO NOT EDIT\n")


@pytest.mark.parametrize("header", [_JQUERY, _TYPEAHEAD])
@pytest.mark.parametrize("folder", ["docs/_static", "static/js", "assets", "public/lib"])
def test_third_party_header_under_asset_dirs_is_vendored(header: str, folder: str) -> None:
    assert code_origin(f"{folder}/lib.js", header) == "vendored"


def test_third_party_header_outside_asset_dirs_stays() -> None:
    assert code_origin("src/lib.js", _JQUERY) == "production"


def test_own_license_header_is_not_vendored() -> None:
    assert code_origin("static/js/boot.js", _OWN_HEADER) == "production"
    assert code_origin("docs/_static/boot.js", _OWN_HEADER) == "docs_example"


def test_own_release_banner_is_not_vendored() -> None:
    banner = "/*! acme v1.2.0 | (c) Acme | MIT License */\n"
    assert code_origin("static/acme.js", banner, project="acme") == "production"
    assert code_origin("static/acme.js", banner, project="other") == "vendored"


def test_header_banner_must_sit_in_a_comment() -> None:
    # A version string in code with a copyright assignment is not a banner.
    text = 'copyright = "2010 Pallets"\nrelease = "Flask 3.0.1"\n'
    assert code_origin("docs/conf.py", text) == "docs_example"
    assert code_origin("static/conf.py", text) == "production"


def test_header_is_read_from_the_first_twenty_lines_only() -> None:
    text = "\n" * 25 + _JQUERY
    assert code_origin("static/js/lib.js", text) == "production"


def test_windows_separators() -> None:
    assert code_origin("docs_src\\tutorial\\app.py") == "docs_example"
